%SIREV 
% A review of IFISS functionality can be found in SIAM review:
%  "Howard Elman, Alison Ramage and David Silvester"
%  "IFISS: A computational laboratory for investigating incompressible flow problems."
%  "http://eprints.ma.man.ac.uk/1969/"
% Figures from this paper can be generated by
% running the script files: sirev_ex3_1 and sirev_ex3_2

%   IFISS scriptfile: DJS; 1 October 2013.
% Copyright (c) 2013 by D.J. Silvester, H.C. Elman and A. Ramage

