/*----------------------------------------------------------------------------

2D Physics Test Program - a cheesy test harness for 2D physics

by Chris Hecker for my Game Developer Magazine articles.  See my homepage
for more information.

NOTE: This is a hacked test program, not a nice example of Windows programming.
physics.cpp the only part of this you should look at!!!

This material is Copyright 1997 Chris Hecker, All Rights Reserved.
It's for you to read and learn from, not to put in your own articles
or books or on your website, etc.  Thank you.

Chris Hecker
checker@d6.com
http://www.d6.com/users/checker

*/

/* Menu Items */
#define MENU_ABOUT			0
#define MENU_EXIT			1
#define MENU_WORLDSPRING	2
#define MENU_BODYSPRING		3
#define MENU_DAMPING		4
#define MENU_GRAVITY		5


