function Y = eulermatrix(X)
phi = X(1); thet = X(2); psi = X(3);
Y = [ cos(psi)*cos(phi) - sin(psi)*cos(thet)*sin(phi), ...
    - sin(psi)*cos(phi) - cos(psi)*cos(thet)*sin(phi), ...
      sin(thet)*sin(phi);
      cos(psi)*sin(phi) + sin(psi)*cos(thet)*cos(phi), ...
    - sin(psi)*sin(phi) + cos(psi)*cos(thet)*cos(phi), ...
    - sin(thet)*cos(phi);
      sin(psi)*sin(thet), cos(psi)*sin(thet), cos(thet)];
