#!/usr/bin/env python
import sys, os, glob
if len(sys.argv) < 3:
    print """
    Usage: newdircvs directoryname suffix1 [suffix2 ... ]
    Example: newdircvs tex c cpp"""; sys.exit(1)

dirname = sys.argv[1];  del sys.argv[1]
if not os.path.isdir(dirname):
    print "directory %s does not exist! % dirname";  sys.exit(1)

os.system("cvs add %s" % dirname)
os.chdir(dirname)
for suffix in sys.argv[1:]:
    files = glob.glob("*.%s" % suffix)
    os.system("cvs add %s" % ' '.join(files))
