#!/usr/bin/env python
import sys, os, re

if len(sys.argv) < 2:
    print "Usage: rmcvs [OPTIONS] file1 file2 ...\n(works as Unix rm)"
    sys.exit(1)

# remove options to rmcvs (-f and so, which have no impact here)
while sys.argv[1][0] == '-':  del sys.argv[1]

for file in sys.argv[1:]:
    if os.path.isdir(file):
        print "rmcvs: cannot remove directores (%s)" % file
        sys.exit(1)

for file in sys.argv[1:]:
    os.remove(file)
    print "removing", file
    os.system("cvs remove %s" % file)
