#!/bin/sh
# start a new project in svn with its own (separate) repository

if [ $# -ne 2 ]; then
    echo "Usage: $0 project_name project_dir"
    echo "project_name is the (short) name of the project"
    echo "project_dir is the (complete) path to the directory containing"
    echo "   the files to be imported"
    exit 1
fi

# let $HOME/svn-repository be the root of all repositories
# and make this directory if it does not exist:
rootrep=$HOME/svn-repository
if [ ! -d $rootrep ]; then
    mkdir $rootrep
fi

project_name=$1
project_dir=$2

# let $project_name be a *new repository*:
# (different projects in different repositories are advantageous in svn)
cd $rootrep
svn admin ${project_name}-repository

# repository directory for the current project:
rep=$rootrep/${project_name}-repository

svn mkdir file://$rep/$project_name \
    -m "create $project_name directory"
svn import file://$rep $project_dir $project_name/trunk \
    -m "initial import of project $project_name"

echo "Project with name $project_name: all files in"
echo "      $project_dir"
echo "are imported. To check out a copy, write"
echo "svn checkout file://$rep desired_destination_dir"


