import networkx as net

o=net.Graph()

o.add_edge('Conrad','Mary')
o.add_edge('Conrad','Cindy')
o.add_edge('Conrad','Alice')
o.add_edge('Alice','Brad')
o.add_edge('Alice','Angie')
o.add_edge('Alice','Jim')
o.add_edge('Cindy','Samuel')
o.add_edge('Cindy','Dave')
o.add_edge('Cindy','Frida')
net.draw(o)

a=net.Graph()
a.add_edge('Cindy','Samuel')
a.add_edge('Cindy','Conrad')
a.add_edge('Samuel','Frida')
a.add_edge('Conrad','Frida')
a.add_edge('Alice','Frida')
a.add_edge('Angie','Frida')
a.add_edge('Dave','Frida')
a.add_edge('Mary','Frida')
a.add_edge('Brad','Mary')
a.add_node('Jim')
net.draw(a)

net.write_pajek(o,'../chapter1/ACME_orgchart.net')
net.write_pajek(a,'../chapter1/ACME_advice.net')