# Can't get nose to work with Python 3, so I'll just whip up a test tool 
# myself...

test:
	@#nosetests -s --with-doctest
	@#python2.6 simpletest *.py
	python2.7 simpletest *.py
	python3.1 simpletest *.py

clean:
	rm -f *.pyc