include ../makefile.in

archive: 
	(cd frame; make archive)
	(cd material; make archive)
	(cd shells; make archive)
	(cd solid1d; make archive)
	(cd solid2d; make archive)
	(cd solid3d; make archive)
	(cd thermal; make archive)

clean: 
	(cd frame; make clean)
	(cd material; make clean)
	(cd shells; make clean)
	(cd solid1d; make clean)
	(cd solid2d; make clean)
	(cd solid3d; make clean)
	(cd thermal; make clean)

