%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%    An Introduction to Scientific Computing          %%%%%%%
%%%%%%%    I. Danaila, P. Joly, S. M. Kaber & M. Postel     %%%%%%%
%%%%%%%                 Springer, 2005                      %%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
close all;clear all;
format long e;

% Glabal variables (mesh description)
global Ns             % Number of vertices
global Nt             % Number of triangles
global XYs            % Coordinates X,Y of the vertices
global Refs           % Labels of vertices
global I123           % Definition of triangles (3 vertices)
global Reft           % Labels of  triangles
global Nomfic         % Mesh file

global txtH % text dimensions

nisol=5;              % Number of iso-contours
ifirst=0;             % Used to remember if the system matrix was calculated

%====================================
% Windows and buttons dimensions
% Screen

set(0, 'Units', 'pixels'); 
rSS = get(0,'ScreenSize');rSS(3:4)=rSS(3:4);

%Windows
leftM=rSS(3)/100;
rightM=leftM;
topM=leftM*5;
btnM=topM;
betwM=leftM;
labelColor=[0.8 0.8 0.8];

%=================================================
% Figure 1 -- set the mesh file and print comments
%=================================================
frmH = (rSS(4)-topM-btnM);
frmW = (rSS(3)-leftM-rightM-betwM)/3;
yPos=btnM;xPos=leftM;
frmPos=[xPos yPos frmW frmH];

a = figure('Units','pixels','Color',labelColor, ...
	'Position',frmPos, ...
	'Tag','Fig1','Name','Wellcome...','Numbertitle','off');

%Text
%frmP=get(a,'Position');
%frmH=frmP(4)-frmP(2);
%frmW=frmP(3)-frmP(1);

txtH=(frmH-topM-btnM)/40;
txtS=txtH;
txtL=leftM;
txtR=txtL;
txtT=txtL;
txtB=txtT;

yPos=frmH-2*txtH-txtT;


%--------------------------------------------credits
yPos=frmH-2*txtH-txtT;
stt = uicontrol('Parent',a, ...
   'Units','pixels', ...
   'FontUnits','pixels',...
   'FontSize',txtH, ...
   'FontWeight','bold', ...
	'ForegroundColor',[1 0 0], ...
	'Position',[txtL yPos frmW-2*txtL 1.5*txtH], ...
	'String','Furnace calculation', ...
	'Style','text', ...
	'Tag','StaticText1');

yPos=yPos-txtS-txtH*4;
stt = uicontrol('Parent',a, ...
	'Units','pixels', ...
	'BackgroundColor',[1 1 1], ...
   'FontUnits','pixels',...  
   'FontSize',txtH, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0.75 0 0], ...
	'HorizontalAlignment','center', ...
	'Position',[txtL yPos frmW-2*txtL txtH*4], ...
	'String',char('Solving the PDE -div(k gradT)=f', 'using a finite elements method' , 'Ionut Danaila, Oct. 2005'), ...
	'Style','text', ...
	'Tag','StaticText2');



%---------------load mesh file--------------
%=================================================
yPos=yPos-txtS-1.5*txtH;
stt = uicontrol('Parent',a, ...
	'Units','pixels', ...
   'FontUnits','pixels',...  
	'FontSize',txtH, ...
	'ForegroundColor',[0 0 1], ...
	'Position',[txtL yPos (frmW-2*txtL)*0.75 1.5*txtH], ...
	'String','Name of the mesh file', ...
	'Style','text', ...
	'Tag','StaticText3');



yPos=yPos-txtS-1.5*txtH;
uifname = uicontrol('Parent',a, ...
	'Units','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','Nomfic=get(uifname,''String'');Nomfic=[Nomfic ''.msh''];', ...
   'FontUnits','pixels',...     
   'FontSize',txtH, ...
	'Position',[txtL yPos (frmW-2*txtL)*0.75 txtH*1.5], ...
	'String','meshFF.msh', ...
	'Style','edit', ...
	'Tag','EditText1');



%--------------------------Start program
%========================================================

icallv=0;
stg = uicontrol('Parent',a, ...
	'Units','pixels', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
   'Callback',['Nomfic=get(uifname,''String'');'...
               'xyD=xyD0;set(stj,''String'',''  '');'...
               'updatej([''Mesh file:  '' Nomfic]);'...
               'Lecture;icallv=icallv+1;'], ...
	'FontSize',txtH, ...
	'ForegroundColor',[0.75 0 0], ...
	'Position',[2*txtL+(frmW-2*txtL)*0.75 yPos (frmW-2*txtL)*0.25-txtL txtH*1.5], ...
	'String','Go', ...
	'Tag','Pushbutton1');



%--------------------------Diary window
%=============================================

global  stj txtD xyD DiaryYM ncarl

% background window for the diary
yPos=yPos-txtS;
frr = uicontrol('Parent',a, ...
	'Units','pixels', ...
	'Position',[txtL txtB frmW-2*txtL yPos-txtB], ...
	'Style','frame', ...
	'Tag','Frame1');



% the diary (use FixedWidth font)
stj = uicontrol('Parent',a, ...
       'Units','pixels', ...
    'FontName','FixedWidth', ...
    'FontUnits','pixels',...     
	'ForegroundColor',[0 0 1], ...
	'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText6');


% position of the array containing the diary
frrD   =get(frr,'Position');

% initialization of the diary
   set(stj,'Position',[1.2*frrD(1) frrD(2)+0.5*frrD(4) 0.95*frrD(3) 0.45*frrD(4)] );
   set(stj,'String','Type the name of the mesh file and click on "Go"');
   
txtD =get(stj,'FontSize'); % get the real size of the font
ncarl=floor(frrD(3)/0.8/txtD); % number of characters on a single line

DiaryXL=frrD(1)+txtD;        % (fixed) Xcoord of the left-corner
DiaryW =frrD(3)-2*txtD;      % (fixed) width of the diary 
DiaryT =frrD(2)+frrD(4)-txtD;% (fixed) top of the diary
DiaryYM=0.9*(frrD(4)-2*txtD); % maximum height of the diary 


DiaryH =1.25*txtD;       % initial height of the diary
xyD=[DiaryXL DiaryT-DiaryH DiaryW DiaryH];
xyD0=xyD;

   