%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%    An Introduction to Scientific Computing          %%%%%%%
%%%%%%%    I. Danaila, P. Joly, S. M. Kaber & M. Postel     %%%%%%%
%%%%%%%                 Springer, 2005                      %%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%====================================================
% Choice of the physical parameters using buttons
%====================================================
updatej(' ***********************')
updatej(' Resistances modelled as Gaussian functions')
updatej(' R(x,y)=Ru/2*exp(-r^2/2/R^2),')
updatej('  where r^2=(x-xr)^2=(y-yr)^2')
updatej(' the results have to be mesh independant')
updatej(' ***********************')

updatej('===> You may print the figure at any time:')
updatej('     type the name of the output (eps) file ')
updatej('     in the menu on the upper left-corner ')
updatej('     and press enter ')
updatej(' ***********************')

updatej('===> Modify the physical parameters (conductivities, number of resistances) in the corresponding menus')
updatej('     Click after on "Run case" to start computation')

%----------------Conductivites
bby=frmH-butB-4*butH;

for k=1:length(Ireft)
   bby=bby-butH;   
   K(k)=1;                   %valeur par default
b = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','text',...
   'Position',[1 bby 0.4*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',CIreft(k,:),...
   'String',['K' num2str(k)]);

bk(k) = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','edit',...
   'Position',[1+0.4*butW bby 0.6*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',[1 1 1],...
   'String',num2str(K(k)),...
   'Callback','for k=1:length(Ireft);K(k)=str2num(get(bk(k),''String''));ichange=1;end;');

end


%----------------Imposed temperatures 

bby=bby-butH;
for k=1:length(Irefd)
   bby=bby-butH;   
   TD(k)=100;   % default value
b = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','text',...
   'Position',[1 bby 0.4*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',CIrefd(k),...
   'String',['TD' num2str(k)]);

bd(k) = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','edit',...
   'Position',[1+0.4*butW bby 0.6*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',[1 1 1],...
   'String',num2str(TD(k)),...
   'Callback','for k=1:length(Irefd);TD(k)=str2num(get(bd(k),''String''));ichange=1;end');
               
end


%----------------Resistances 

bby=bby-1.5*butH;
NbR=1;          % 1 resistance (default configuration)  

b = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','text',...
   'Position',[1 bby butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'String','Resistances');

bby=bby-butH;

b = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','text',...
   'Position',[1 bby 0.4*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'String','NbR');


bnbr = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','edit',...
   'Position',[1+0.4*butW bby 0.6*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',[1 1 1],...
   'String',num2str(NbR),...
   'Callback','NbR=str2num(get(bnbr,''String''));');

bby=bby-butH;

Rr=0.08;           % radius of the Gaussian modelling  a resistance
b = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','text',...
   'Position',[1 bby 0.4*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'String','R');


brr = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','edit',...
   'Position',[1+0.4*butW bby 0.6*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',[1 1 1],...
   'String',num2str(Rr),...
   'Callback','Rr=str2num(get(brr,''String''));');

bby=bby-butH;

RU=25000;           % default value for a resistance intensity
b = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','text',...
   'Position',[1 bby 0.4*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'String','Ru');


bru = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','edit',...
   'Position',[1+0.4*butW bby 0.6*butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',[1 1 1],...
   'String',num2str(RU),...
   'Callback','RU=str2num(get(bru,''String''));');


% Start the computation (linear problem)
bby=bby-3*butH;


scalc = uicontrol('Parent',fg2, ...
	'Units','pixels', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
   'Callback',['updatej(''Values of the conductivites for each domain (Label/Value)'');'...
               'for k=1:length(Ireft);K(k)=str2num(get(bk(k),''String''));updatej([''   '' num2str(Ireft(k)) ''    '' num2str(K(k))]);end;'...
               'updatej(''Values of the imposed temp (Label/Value)'');'...
               'for k=1:length(Irefd);TD(k)=str2num(get(bd(k),''String''));updatej([''   '' num2str(Irefd(k)) ''    '' num2str(TD(k))]);end;'...
               'NbR=str2num(get(bnbr,''String''));'...
               'updatej([''Number of resistances=  '' num2str(NbR)]);'...
               'RU=str2num(get(bru,''String''));'...
               'updatej([''Value of a resistance =  '' num2str(RU)]);'...
               'updatej(''***********************'');'...
               'figure(fg2);Show_border(xb,yb,fg2);updatej([''===>Choose the resistance location (click '' num2str(NbR) '' times in the furnace domain)'']);'...
               'for k=1:NbR;XYr(k,:)=ginput(1);'...
               'updatej([''R'' num2str(k) ''  X='' num2str(XYr(k,1))  ''  Y='' num2str(XYr(k,2))]);end;'...
               'updatej(''***********************'');'...
               'Calculer;'], ...
	'FontSize',txtH, ...
	'ForegroundColor',[0.75 0 0], ...
	'Position',[1 bby butW butH], ...
	'String','Run case', ...
	'Tag','Pushbuttonc');
