build :
	cd Source && make -f makefile.lnx
	cd Renderers && make -f makefile.lnx
	cd Applications && make -f makefile.lnx

clean :
	cd Source && make clean -f makefile.lnx
	cd Renderers && make clean  -f makefile.lnx
	cd Applications && make clean -f makefile.lnx
