"""
DSMC3.py
Generated by Claude.ai
Complete Python translation of G.A. Bird's DSMC3.FOR (Fortran 77).
Three-dimensional steady flow, rectangular domain, uniform cells.

Notes on translation:
  - All Fortran COMMON blocks → State dataclass
  - All arrays are 0-based (Fortran 1-based indices shifted by -1 throughout)
  - RF(0) → rng.random() via numpy default_rng
  - GOTO loops → while/continue/break
  - ERF → math.erf, GAM → math.gamma
  - Restart via pickle
  - SI units throughout
"""

import math
import pickle
import sys
import numpy as np
from dataclasses import dataclass, field
from typing import List

# ---------------------------------------------------------------------------
# PARAMETER constants  (must match DATA3 setup)
# ---------------------------------------------------------------------------
MNM  = 70000   # max molecules
MNC  = 9720    # max cells
MNSC = 9720    # max sub-cells
MNSP = 1       # max species
MNSG = 1       # max collision groups
MNSE = 900     # max surface elements
MNMR = 1       # 1 if monatomic, MNM otherwise
MNMS = 1       # 1 if single species, MNM otherwise

# ---------------------------------------------------------------------------
# Random number generator  (module-level, seeded once)
# ---------------------------------------------------------------------------
rng = np.random.default_rng(seed=12345)

def rf():
    """Uniform random fraction in (0,1) — replaces RF(0) everywhere."""
    return rng.random()

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def rvelc(vmp):
    """
    Generate two random thermal velocity components at most-probable speed vmp.
    Replaces RVELC(U, V, VMP).  Returns (u, v).
    Based on Bird eqns (C10) and (C12).
    """
    a = math.sqrt(-math.log(rf()))
    b = 2.0 * math.pi * rf()
    u = a * math.sin(b) * vmp
    v = a * math.cos(b) * vmp
    return u, v

def gamma_func(x):
    """
    Gamma function approximation matching Bird's GAM(X).
    Uses the same polynomial as the Fortran, but math.gamma is more accurate.
    """
    return math.gamma(x)

def erf_func(s):
    """Error function — replaces the Fortran ERF(S)."""
    return math.erf(s)

def srot(temp, idf):
    """
    Sample equilibrium rotational energy at temperature temp
    with idf rotational degrees of freedom.
    Replaces SROT(PR, TEMP, IDF).  Returns PR.
    """
    boltz = 1.380622e-23
    if idf == 2:
        pr = -math.log(rf()) * boltz * temp
    else:
        a = 0.5 * idf - 1.0
        while True:
            erm = rf() * 10.0
            b = ((erm / a) ** a) * math.exp(a - erm)
            if b >= rf():
                break
        pr = erm * boltz * temp
    return pr

def lbs(xma, xmb):
    """
    Select a Larsen-Borgnakke energy ratio using eqn (11.9).
    Replaces LBS(XMA, XMB, ERM).  Returns erm.
    """
    while True:
        erm = rf()
        if xma < 1e-6 or xmb < 1e-6:
            if xma < 1e-6 and xmb < 1e-6:
                return erm
            if xma < 1e-6:
                p = (1.0 - erm) ** xmb
            else:
                p = (1.0 - erm) ** xma
        else:
            p = (((xma + xmb) * erm / xma) ** xma) * \
                (((xma + xmb) * (1.0 - erm) / xmb) ** xmb)
        if p >= rf():
            return erm

# ---------------------------------------------------------------------------
# State  — replaces all Fortran COMMON blocks
# ---------------------------------------------------------------------------

class State:
    def __init__(self):
        # Physical constants  (/CONST/)
        self.PI    = math.pi
        self.SPI   = math.sqrt(math.pi)
        self.BOLTZ = 1.380622e-23

        # --- /MOLS3/ ---
        self.NM  = 0                                  # current molecule count
        self.PP  = np.zeros((3, MNM), dtype=float)    # positions (0=x,1=y,2=z)
        self.PV  = np.zeros((3, MNM), dtype=float)    # velocities
        self.IPL = np.zeros(MNM, dtype=int)           # sub-cell pointer (0-based)
        self.IPS = np.zeros(MNM, dtype=int)           # species index (0-based)
        self.IR  = np.zeros(MNM, dtype=int)           # cross-reference array

        # --- /MOLSR/ ---
        self.PR  = np.zeros(max(MNMR, MNM) if MNMR > 1 else MNMR, dtype=float)

        # --- /CELL3/ ---
        self.CC   = 0.0                                       # cell volume
        self.CG   = np.zeros((6, MNC), dtype=float)          # cell coords
        self.IC   = np.zeros((2, MNC, MNSG), dtype=int)      # cell molecule index
        self.ISC  = np.zeros(MNSC, dtype=int)                 # sub-cell → cell map
        self.CCG  = np.zeros((2, MNC, MNSG, MNSG), dtype=float)
        self.ISCG = np.zeros((2, MNSC, MNSG), dtype=int)
        self.IG   = np.zeros((2, MNSG), dtype=int)
        self.NCX  = 0
        self.NCY  = 0
        self.NCZ  = 0

        # --- /GAS/ ---
        self.SP  = np.zeros((5, MNSP), dtype=float)
        self.SPM = np.zeros((6, MNSP, MNSP), dtype=float)
        self.ISP = np.zeros(MNSP, dtype=int)          # collision group (0-based)

        # --- /GASR/ ---
        self.SPR  = np.zeros((3, MNSP, MNSP), dtype=float)
        self.ISPR = np.zeros((3, MNSP), dtype=int)
        self.CT   = np.zeros(MNC, dtype=float)         # cell temperature

        # --- /SAMP3/ ---
        self.COL  = np.zeros((MNSP, MNSP), dtype=float)
        self.NCOL = 0.0
        self.MOVT = 0.0
        self.SELT = 0.0
        self.SEPT = 0.0
        self.CS   = np.zeros((7, MNC, MNSP), dtype=float)
        self.TIME = 0.0
        self.NPR  = 0
        self.NSMP = 0
        self.FND  = 0.0
        self.FTMP = 273.0
        self.TIMI = 0.0
        self.FSP  = np.zeros(MNSP, dtype=float)
        self.ISPD = 0
        self.VFX  = 0.0
        self.VFY  = 0.0
        self.VFZ  = 0.0

        # --- /SAMPR/ ---
        self.CSR = np.zeros((MNC, MNSP), dtype=float)

        # --- /SAMPS/ ---
        self.CSS = np.zeros((11, MNSE, MNSP), dtype=float)
        self.ICS = np.zeros(MNSE, dtype=int)           # cell adjacent to element

        # --- /COMP/ ---
        self.FNUM = 0.0
        self.DTM  = 0.0
        self.NIS  = 0
        self.NSP  = 0
        self.NPS  = 0
        self.NPT  = 0

        # --- /GEOM3/ ---
        self.NSCX  = 1
        self.NSCY  = 1
        self.NSCZ  = 1
        self.CB    = np.zeros(6, dtype=float)
        self.IB    = np.zeros(6, dtype=int)
        self.ISURF = np.zeros(2, dtype=int)
        self.LIMS  = np.zeros((2, 5), dtype=int)       # 1-based cell numbers kept
        self.ISG   = 0
        self.IIS   = 0
        self.TSURF = np.zeros(2, dtype=float)
        self.BME   = np.zeros((6, MNSP), dtype=float)
        self.BMR   = np.zeros((6, MNSP), dtype=float)
        self.CW    = 0.0   # cell width  (x)
        self.FW    = 0.0   # flow width
        self.CH    = 0.0   # cell height (y)
        self.FH    = 0.0   # flow height
        self.FD    = 0.0   # flow depth  (z)
        self.CD    = 0.0   # cell depth
        self.IJET  = 0
        self.XJ    = 0.0
        self.ZJ    = 0.0
        self.RJ    = 0.0
        self.TMPJ  = 0.0
        self.FNDJ  = 0.0
        self.FVJ   = 0.0
        self.FSPJ  = np.zeros(MNSP, dtype=float)
        self.BMEJ  = np.zeros(MNSP, dtype=float)
        self.BMRJ  = np.zeros(MNSP, dtype=float)
        self.BFND  = 0.0

        # --- /ELAST/ — collision temporaries shared between select/elastic/inelr
        self.VRC  = np.zeros(3, dtype=float)
        self.VRR  = 0.0
        self.VR   = 0.0
        self.L    = 0     # molecule index L  (0-based)
        self.M    = 0     # molecule index M  (0-based)
        self.LS   = 0     # species of L      (0-based)
        self.MS   = 0     # species of M      (0-based)
        self.CVR  = 0.0
        self.MM   = 0     # collision group indices (0-based)
        self.NN   = 0
        self.N    = 0     # current cell      (0-based)

# ---------------------------------------------------------------------------
# DATA3  — problem-specific input
# ---------------------------------------------------------------------------

def data3(s: State):
    """
    Defines all input data for a particular run.
    Mirrors DATA3.FOR exactly.  All cell/row indices are kept as
    1-based integers here (matching the Fortran comments) and converted
    to 0-based only where array indexing is performed in the other routines.
    """
    s.NCX = 30
    s.NCY = 18
    s.NCZ = 18
    s.NSCX = 1
    s.NSCY = 1
    s.NSCZ = 1
    s.IIS = 1
    s.ISG = 1
    s.FTMP = 300.0
    s.FND  = 1.0e20
    s.VFX  = 1936.0
    s.VFY  = 0.0
    s.VFZ  = 0.0
    s.FSP[0] = 1.0

    s.FNUM = 0.2e14
    s.DTM  = 2.0e-6

    s.CB[0] = 0.0;  s.CB[1] = 0.3
    s.CB[2] = 0.0;  s.CB[3] = 0.18
    s.CB[4] = 0.0;  s.CB[5] = 0.18

    # IB: 1=stream, 2=symmetry, 3=vacuum  (stored 0-based index → kept as-is,
    #     values 1/2/3 are used by logic not array indexing)
    s.IB[0] = 1;  s.IB[1] = 1
    s.IB[2] = 2;  s.IB[3] = 1
    s.IB[4] = 2;  s.IB[5] = 1

    # Surface 1  (ISURF=1 means normal in +y direction)
    s.ISURF[0] = 1
    s.LIMS[0, 0] = 1   # cell row along which surface lies
    s.LIMS[0, 1] = 6   # lower x cell limit
    s.LIMS[0, 2] = 30  # upper x cell limit
    s.LIMS[0, 3] = 1   # lower z cell limit
    s.LIMS[0, 4] = 18  # upper z cell limit
    s.TSURF[0]   = 1000.0

    # Surface 2  (ISURF=5 means normal in +z direction)
    s.ISURF[1] = 5
    s.LIMS[1, 0] = 1
    s.LIMS[1, 1] = 6
    s.LIMS[1, 2] = 30
    s.LIMS[1, 3] = 1
    s.LIMS[1, 4] = 18
    s.TSURF[1]   = 1000.0

    s.IJET = 0

    # Species 1 (argon-like)
    s.SP[0, 0] = 4.17e-10   # reference diameter
    s.SP[1, 0] = 273.0      # reference temperature
    s.SP[2, 0] = 0.81       # viscosity-temperature index
    s.SP[3, 0] = 1.0        # 1/VSS scattering parameter (1=VHS)
    s.SP[4, 0] = 6.63e-26   # molecular mass

    s.ISPR[0, 0] = 0        # rotational DOF  (monatomic)
    s.SPR[0, 0, 0] = 1.0
    s.ISPR[1, 0] = 0
    s.ISP[0] = 0            # collision group (0-based; Fortran had ISP(1)=1)

    s.NIS = 2
    s.NSP = 10
    s.NPS = 15
    s.NPT = 10000

# ---------------------------------------------------------------------------
# INIT3
# ---------------------------------------------------------------------------

def init3(s: State):
    """Initialise simulation: set constants, call data3, build geometry,
    place initial molecules, compute boundary fluxes."""

    # --- defaults ---
    s.FND  = 0.0
    s.FTMP = 273.0
    s.VFX = s.VFY = s.VFZ = 0.0
    for n in range(6):
        s.IB[n] = 3
        for l in range(MNSP):
            s.ISP[l] = 0      # 0-based group
            s.FSP[l] = 0.0
            s.BME[n, l] = 0.0
            s.BMR[n, l] = 0.0
    s.IJET = 0
    for l in range(MNSP):
        s.BMEJ[l] = 0.0
        s.BMRJ[l] = 0.0

    data3(s)

    # --- cross-collision / mixture data ---
    if MNSP == 1:
        s.ISPD = 0

    for n in range(MNSP):
        for m in range(MNSP):
            if s.ISPR[2, n] == 0 and m != n:
                s.SPR[0, n, m] = s.SPR[0, n, n]
                s.SPR[1, n, m] = s.SPR[1, n, n]
                s.SPR[2, n, m] = s.SPR[2, n, n]
            if s.ISPD == 0 or n == m:
                s.SPM[0, n, m] = 0.25 * s.PI * (s.SP[0, n] + s.SP[0, m]) ** 2
                s.SPM[1, n, m] = 0.5 * (s.SP[1, n] + s.SP[1, m])
                s.SPM[2, n, m] = 0.5 * (s.SP[2, n] + s.SP[2, m])
                s.SPM[3, n, m] = 0.5 * (s.SP[3, n] + s.SP[3, m])
            else:
                s.SPM[0, n, m] = s.PI * s.SPM[0, n, m] ** 2
            # reduced mass  eqn (2.7)
            s.SPM[4, n, m] = (s.SP[4, n] / (s.SP[4, n] + s.SP[4, m])) * s.SP[4, m]
            s.SPM[5, n, m] = gamma_func(2.5 - s.SPM[2, n, m])

    # --- initialise counters ---
    s.TIME = 0.0
    s.NM   = 0
    s.NPR  = 0
    s.NCOL = 0.0
    s.MOVT = 0.0
    s.SELT = 0.0
    s.SEPT = 0.0
    s.COL[:, :] = 0.0

    # --- geometry ---
    s.FW = s.CB[1] - s.CB[0]
    s.FH = s.CB[3] - s.CB[2]
    s.FD = s.CB[5] - s.CB[4]
    s.CW = s.FW / s.NCX
    s.CH = s.FH / s.NCY
    s.CD = s.FD / s.NCZ
    s.CC = s.CW * s.CH * s.CD

    # set cell coordinates  (0-based cell index m)
    for mz in range(s.NCZ):
        for my in range(s.NCY):
            for mx in range(s.NCX):
                m = mz * s.NCX * s.NCY + my * s.NCX + mx   # 0-based
                s.CT[m] = s.FTMP
                # x
                s.CG[0, m] = s.CB[0] + mx * s.CW
                s.CG[1, m] = s.CG[0, m] + s.CW
                # y
                s.CG[2, m] = s.CB[2] + my * s.CH
                s.CG[3, m] = s.CG[2, m] + s.CH
                # z
                s.CG[4, m] = s.CB[4] + mz * s.CD
                s.CG[5, m] = s.CG[4, m] + s.CD
                # initialise CCG
                for lg in range(MNSG):
                    for kg in range(MNSG):
                        s.CCG[1, m, lg, kg] = rf()
                        s.CCG[0, m, lg, kg] = (s.SPM[0, 0, 0] * 300.0 *
                                                math.sqrt(s.FTMP / 300.0))

    # set sub-cells  (each sub-cell maps to its parent cell, 0-based)
    for n in range(MNC):
        for j in range(s.NSCZ):
            for mv in range(s.NSCY):
                for k in range(s.NSCX):
                    ll = (n * s.NSCX * s.NSCY * s.NSCZ +
                          j * s.NSCX * s.NSCY +
                          mv * s.NSCX + k)
                    if ll < MNSC:
                        s.ISC[ll] = n

    # --- place initial molecules ---
    if s.IIS > 0 and s.ISG > 0:
        for l in range(MNSP):
            rem = 0.0
            vmp = math.sqrt(2.0 * s.BOLTZ * s.FTMP / s.SP[4, l])
            for n in range(MNC):
                a = s.FND * s.CC * s.FSP[l] / s.FNUM + rem
                if n < MNC - 1:
                    mm = int(a)
                    rem = a - mm
                else:
                    mm = round(a)
                for _ in range(mm):
                    if s.NM < MNM:
                        ni = s.NM          # 0-based molecule index
                        s.NM += 1
                        if MNSP > 1:
                            s.IPS[ni] = l
                        s.PP[0, ni] = s.CG[0, n] + rf() * (s.CG[1, n] - s.CG[0, n])
                        s.PP[1, ni] = s.CG[2, n] + rf() * (s.CG[3, n] - s.CG[2, n])
                        s.PP[2, ni] = s.CG[4, n] + rf() * (s.CG[5, n] - s.CG[4, n])
                        ncolm = int((s.PP[0, ni] - s.CG[0, n]) * (s.NSCX - 0.001) / s.CW) + 1
                        nrow  = int((s.PP[1, ni] - s.CG[2, n]) * (s.NSCY - 0.001) / s.CH) + 1
                        nslc  = int((s.PP[2, ni] - s.CG[4, n]) * (s.NSCZ - 0.001) / s.CD) + 1
                        ipl = (n * s.NSCX * s.NSCY * s.NSCZ +
                               (nslc - 1) * s.NSCX * s.NSCY +
                               (nrow - 1) * s.NSCX + (ncolm - 1))
                        s.IPL[ni] = max(0, min(MNSC - 1, ipl))
                        for k in range(3):
                            u, v = rvelc(vmp)
                            s.PV[k, ni] = u       # second component discarded per call
                        # re-do properly: each component independently
                        u, _ = rvelc(vmp);  s.PV[0, ni] = u + s.VFX
                        u, _ = rvelc(vmp);  s.PV[1, ni] = u + s.VFY
                        u, _ = rvelc(vmp);  s.PV[2, ni] = u + s.VFZ
                        if s.ISPR[0, l] > 0:
                            s.PR[ni] = srot(s.FTMP, s.ISPR[0, l])
        print(f" {s.NM} MOLECULES")

    # --- boundary entry fluxes ---
    if s.IIS > 0:
        for n in range(6):
            if s.IB[n] == 1:
                print(f" side {n+1}")
                for l in range(MNSP):
                    vmp = math.sqrt(2.0 * s.BOLTZ * s.FTMP / s.SP[4, l])
                    if   n == 0: sc =  s.VFX / vmp
                    elif n == 1: sc = -s.VFX / vmp
                    elif n == 2: sc =  s.VFY / vmp
                    elif n == 3: sc = -s.VFY / vmp
                    elif n == 4: sc =  s.VFZ / vmp
                    else:        sc = -s.VFZ / vmp
                    if abs(sc) < 10.1:
                        a = (math.exp(-sc*sc) + s.SPI * sc * (1.0 + erf_func(sc))) / (2.0 * s.SPI)
                    elif sc > 10.0:
                        a = sc
                    else:
                        a = 0.0
                    if n < 2:
                        s.BME[n, l] = s.FND * s.FSP[l] * a * vmp * s.DTM * s.FH * s.FD / s.FNUM
                    elif n < 4:
                        s.BME[n, l] = s.FND * s.FSP[l] * a * vmp * s.DTM * s.FW * s.FD / s.FNUM
                    else:
                        s.BME[n, l] = s.FND * s.FSP[l] * a * vmp * s.DTM * s.FH * s.FW / s.FNUM
                    print(f"   species {l+1} entering mols {s.BME[n, l]:.4f}")

    # --- jet fluxes ---
    if s.IJET > 0:
        for l in range(MNSP):
            vmp = math.sqrt(2.0 * s.BOLTZ * s.TMPJ / s.SP[4, l])
            sc  = s.FVJ / vmp
            if abs(sc) < 10.1:
                a = (math.exp(-sc*sc) + s.SPI * sc * (1.0 + erf_func(sc))) / (2.0 * s.SPI)
            elif sc > 10.0:
                a = sc
            else:
                a = 0.0
            aj = s.PI * s.RJ * s.RJ
            if s.IJET == 2: aj *= 0.5
            if s.IJET == 3: aj *= 0.25
            s.BMEJ[l] = s.FNDJ * s.FSPJ[l] * a * vmp * s.DTM * aj / s.FNUM
            print(f"   entering mols in jet {s.BMEJ[l]:.4f}")

# ---------------------------------------------------------------------------
# REMOVE
# ---------------------------------------------------------------------------

def remove(s: State, n: int):
    """
    Remove molecule n (0-based) by replacing it with the last molecule NM-1.
    Decrements NM and returns the new n (n-1, because the caller loop
    should re-examine the slot, now occupied by the formerly-last molecule).
    """
    last = s.NM - 1
    s.PP[:, n]  = s.PP[:, last]
    s.PV[:, n]  = s.PV[:, last]
    s.IPL[n]    = s.IPL[last]
    if MNMR > 1:
        s.PR[n] = s.PR[last]
    if MNSP > 1:
        s.IPS[n] = s.IPS[last]
    s.NM -= 1
    return n - 1

# ---------------------------------------------------------------------------
# REFLECT3
# ---------------------------------------------------------------------------

def reflect3(s: State, n: int, ks: int, k: int, xc: float, yc: float, zc: float, mc: int):
    """
    Reflect molecule n (0-based) off surface ks (0-based) at element k (0-based),
    position (xc,yc,zc), adjacent cell mc (0-based).
    Samples incident/reflected surface properties and updates velocity.
    """
    if s.ICS[k] == 0:
        s.ICS[k] = mc + 1    # store 1-based cell reference (0 = unvisited sentinel)

    l = s.IPS[n] if MNSP > 1 else 0

    # --- sample incident ---
    s.CSS[0, k, l] += 1.0
    isurf_val = s.ISURF[ks]
    m5l = s.SP[4, l]   # molecular mass
    vx, vy, vz = s.PV[0, n], s.PV[1, n], s.PV[2, n]

    if   isurf_val == 1:
        s.CSS[1, k, l] -= m5l * vy
        s.CSS[3, k, l] += m5l * vx
        s.CSS[9, k, l] += m5l * vz
    elif isurf_val == 2:
        s.CSS[1, k, l] += m5l * vy
        s.CSS[3, k, l] += m5l * vx
        s.CSS[9, k, l] += m5l * vz
    elif isurf_val == 3:
        s.CSS[1, k, l] -= m5l * vx
        s.CSS[3, k, l] += m5l * vy
        s.CSS[9, k, l] += m5l * vz
    elif isurf_val == 4:
        s.CSS[1, k, l] += m5l * vx
        s.CSS[3, k, l] += m5l * vy
        s.CSS[9, k, l] += m5l * vz
    elif isurf_val == 5:
        s.CSS[1, k, l] -= m5l * vz
        s.CSS[3, k, l] += m5l * vx
        s.CSS[9, k, l] += m5l * vy
    elif isurf_val == 6:
        s.CSS[1, k, l] += m5l * vz
        s.CSS[3, k, l] += m5l * vx
        s.CSS[9, k, l] += m5l * vy

    s.CSS[4, k, l] += 0.5 * m5l * (vx**2 + vy**2 + vz**2)
    if MNMR > 1:
        s.CSS[6, k, l] += s.PR[n]

    # --- reflection ---
    if s.TSURF[ks] < 0.0:
        # specular
        if isurf_val in (1, 2): s.PV[1, n] = -s.PV[1, n]
        if isurf_val in (3, 4): s.PV[0, n] = -s.PV[0, n]
        if isurf_val in (5, 6): s.PV[2, n] = -s.PV[2, n]
    else:
        # diffuse
        vmp = math.sqrt(2.0 * s.BOLTZ * s.TSURF[ks] / m5l)
        if isurf_val == 1:
            s.PV[1, n] = math.sqrt(-math.log(rf())) * vmp
            u, v = rvelc(vmp);  s.PV[0, n] = u;  s.PV[2, n] = v
        elif isurf_val == 2:
            s.PV[1, n] = -math.sqrt(-math.log(rf())) * vmp
            u, v = rvelc(vmp);  s.PV[0, n] = u;  s.PV[2, n] = v
        elif isurf_val == 3:
            s.PV[0, n] = math.sqrt(-math.log(rf())) * vmp
            u, v = rvelc(vmp);  s.PV[1, n] = u;  s.PV[2, n] = v
        elif isurf_val == 4:
            s.PV[0, n] = -math.sqrt(-math.log(rf())) * vmp
            u, v = rvelc(vmp);  s.PV[1, n] = u;  s.PV[2, n] = v
        elif isurf_val == 5:
            s.PV[2, n] = math.sqrt(-math.log(rf())) * vmp
            u, v = rvelc(vmp);  s.PV[1, n] = u;  s.PV[0, n] = v
        elif isurf_val == 6:
            s.PV[2, n] = -math.sqrt(-math.log(rf())) * vmp
            u, v = rvelc(vmp);  s.PV[1, n] = u;  s.PV[0, n] = v
        if s.ISPR[0, l] > 0:
            s.PR[n] = srot(s.TSURF[ks], s.ISPR[0, l])

    # --- reposition just off surface ---
    if   isurf_val == 1:
        s.PP[0, n] = xc;  s.PP[1, n] = yc + 0.001 * s.CH;  s.PP[2, n] = zc
    elif isurf_val == 2:
        s.PP[0, n] = xc;  s.PP[1, n] = yc - 0.001 * s.CH;  s.PP[2, n] = zc
    elif isurf_val == 3:
        s.PP[0, n] = xc + 0.001 * s.CW;  s.PP[1, n] = yc;  s.PP[2, n] = zc
    elif isurf_val == 4:
        s.PP[0, n] = xc - 0.001 * s.CW;  s.PP[1, n] = yc;  s.PP[2, n] = zc
    elif isurf_val == 5:
        s.PP[0, n] = xc;  s.PP[1, n] = yc;  s.PP[2, n] = zc + 0.001 * s.CD
    elif isurf_val == 6:
        s.PP[0, n] = xc;  s.PP[1, n] = yc;  s.PP[2, n] = zc - 0.001 * s.CD

    s.IPL[n] = mc * s.NSCX * s.NSCY * s.NSCZ   # first sub-cell of cell mc

    # --- sample reflected ---
    vx2, vy2, vz2 = s.PV[0, n], s.PV[1, n], s.PV[2, n]
    if   isurf_val == 1: s.CSS[2, k, l] += m5l * vy2
    elif isurf_val == 2: s.CSS[2, k, l] -= m5l * vy2
    elif isurf_val == 3: s.CSS[2, k, l] += m5l * vx2
    elif isurf_val == 4: s.CSS[2, k, l] -= m5l * vx2
    elif isurf_val == 5: s.CSS[2, k, l] += m5l * vz2
    elif isurf_val == 6: s.CSS[2, k, l] -= m5l * vz2

    if isurf_val < 3:
        s.CSS[8, k, l]  -= m5l * vx2
        s.CSS[10, k, l] -= m5l * vz2
    elif isurf_val < 5:
        s.CSS[8, k, l]  -= m5l * vy2
        s.CSS[10, k, l] -= m5l * vz2
    else:
        s.CSS[8, k, l]  -= m5l * vx2
        s.CSS[10, k, l] -= m5l * vy2

    s.CSS[5, k, l] -= 0.5 * m5l * (vx2**2 + vy2**2 + vz2**2)
    if MNMR > 1:
        s.CSS[7, k, l] -= s.PR[n]

# ---------------------------------------------------------------------------
# MOVE3
# ---------------------------------------------------------------------------

def move3(s: State):
    """
    Move all NM molecules over DTM.  Handle surface reflections, boundary
    conditions, and entry of new molecules.
    Mirrors MOVE3.FOR with GOTO replaced by while/continue.
    """
    ift = -1   # negative → molecules have not yet entered this step
    n = 0
    while n < s.NM:
        if ift < 0:
            at = s.DTM
        else:
            at = rf() * s.DTM

        # inner loop  (replaces GO TO 150)
        while True:
            s.MOVT += 1
            msc = s.IPL[n]
            mc  = s.ISC[msc]

            # bounds check — remove strayed molecules
            xi = s.PP[0, n]
            yi = s.PP[1, n]
            zi = s.PP[2, n]
            if (xi + 0.00001 * s.CW < s.CB[0] or xi - 0.00001 * s.CW > s.CB[1] or
                yi + 0.00001 * s.CH < s.CB[2] or yi - 0.00001 * s.CH > s.CB[3] or
                zi + 0.00001 * s.CD < s.CB[4] or zi - 0.00001 * s.CD > s.CB[5]):
                n = remove(s, n)
                break    # go to next n

            dx = s.PV[0, n] * at
            dy = s.PV[1, n] * at
            dz = s.PV[2, n] * at
            x  = xi + dx
            y  = yi + dy
            z  = zi + dz

            # --- surface intersection check ---
            hit_surface = False
            for ks in range(2):
                if s.ISURF[ks] == 0:
                    continue
                isurf_val = s.ISURF[ks]

                if isurf_val in (1, 2):
                    l1 = s.LIMS[ks, 0]
                    ys = (l1 - 1) * s.CH + s.CB[2]
                    cond = ((isurf_val == 1 and yi > ys and y < ys) or
                            (isurf_val == 2 and yi < ys and y > ys))
                    if cond and abs(dy) > 0.0:
                        xc = xi + (ys - yi) * dx / dy
                        zc = zi + (ys - yi) * dz / dy
                        if (s.CB[0] < xc < s.CB[1] and s.CB[4] < zc < s.CB[5]):
                            l2, l3 = s.LIMS[ks, 1], s.LIMS[ks, 2]
                            l4, l5 = s.LIMS[ks, 3], s.LIMS[ks, 4]
                            xsu = (l2 - 1) * s.CW + s.CB[0]
                            xsd = l3 * s.CW + s.CB[0]
                            zsu = (l4 - 1) * s.CD + s.CB[4]
                            zsd = l5 * s.CD + s.CB[4]
                            if xsu < xc < xsd and zsu < zc < zsd:
                                mcx = int((xc - s.CB[0]) / s.CW + 0.99999)
                                mcx = max(0, min(s.NCX - 1, mcx))
                                mcz = int((zc - s.CB[4]) / s.CD + 0.99999)
                                mcz = max(0, min(s.NCZ - 1, mcz))
                                mcsx = mcx - (l2 - 1)
                                mcsz = mcz - (l4 - 1)
                                mcs  = mcsz * (l3 - l2 + 1) + mcsx  # 0-based
                                if ks == 1:
                                    mcs += (s.LIMS[0, 2] - s.LIMS[0, 1] + 1) * \
                                           (s.LIMS[0, 4] - s.LIMS[0, 3] + 1)
                                mc2 = mcz * s.NCX * s.NCY + mcx
                                if isurf_val == 1:
                                    mc2 += (l1 - 1) * s.NCX
                                else:
                                    mc2 += (l1 - 2) * s.NCX
                                at = at * (y - ys) / dy
                                reflect3(s, n, ks, mcs, xc, ys, zc, mc2)
                                hit_surface = True
                                break

                elif isurf_val in (3, 4):
                    l1 = s.LIMS[ks, 0]
                    xs_val = (l1 - 1) * s.CW + s.CB[0]
                    cond = ((isurf_val == 3 and xi > xs_val and x < xs_val) or
                            (isurf_val == 4 and xi < xs_val and x > xs_val))
                    if cond and abs(dx) > 0.0:
                        yc = yi + (xs_val - xi) * dy / dx
                        zc = zi + (xs_val - xi) * dz / dx
                        if s.CB[2] < yc < s.CB[3] and s.CB[4] < zc < s.CB[5]:
                            l2, l3 = s.LIMS[ks, 1], s.LIMS[ks, 2]
                            l4, l5 = s.LIMS[ks, 3], s.LIMS[ks, 4]
                            ysu = (l2 - 1) * s.CH + s.CB[2]
                            ysd = l3 * s.CH + s.CB[2]
                            zsu = (l4 - 1) * s.CD + s.CB[4]
                            zsd = l5 * s.CD + s.CB[4]
                            if ysu < yc < ysd and zsu < zc < zsd:
                                mcy = int((yc - s.CB[2]) / s.CH + 0.99999)
                                mcy = max(0, min(s.NCY - 1, mcy))
                                mcz = int((zc - s.CB[4]) / s.CD + 0.99999)
                                mcz = max(0, min(s.NCZ - 1, mcz))
                                mcsy = mcy - (l2 - 1)
                                mcsz = mcz - (l4 - 1)
                                mcs  = mcsz * (l3 - l2 + 1) + mcsy
                                if ks == 1:
                                    mcs += (s.LIMS[0, 2] - s.LIMS[0, 1] + 1) * \
                                           (s.LIMS[0, 4] - s.LIMS[0, 3] + 1)
                                mc2 = mcz * s.NCX * s.NCY + (mcy) * s.NCX
                                if isurf_val == 3:
                                    mc2 += l1       # l1 is 1-based → becomes 0-based +1 offset
                                else:
                                    mc2 += l1 - 1
                                at = at * (x - xs_val) / dx
                                reflect3(s, n, ks, mcs, xs_val, yc, zc, mc2)
                                hit_surface = True
                                break

                elif isurf_val in (5, 6):
                    l1 = s.LIMS[ks, 0]
                    if l1 <= s.NCZ:
                        zs = (l1 - 1) * s.CD + s.CB[4]
                    else:
                        zs = s.CB[5]
                        l1 -= 1
                    cond = ((isurf_val == 5 and zi > zs and z < zs) or
                            (isurf_val == 6 and zi < zs and z > zs))
                    if cond and abs(dz) > 0.0:
                        yc = yi + (zs - zi) * dy / dz
                        xc = xi + (zs - zi) * dx / dz
                        if s.CB[0] < xc < s.CB[1] and s.CB[2] < yc < s.CB[3]:
                            l2, l3 = s.LIMS[ks, 1], s.LIMS[ks, 2]
                            l4, l5 = s.LIMS[ks, 3], s.LIMS[ks, 4]
                            xsu = (l2 - 1) * s.CW + s.CB[0]
                            xsd = l3 * s.CW + s.CB[0]
                            ysu = (l4 - 1) * s.CH + s.CB[2]
                            ysd = l5 * s.CH + s.CB[2]
                            if xsu < xc < xsd and ysu < yc < ysd:
                                mcy = int((yc - s.CB[2]) / s.CH + 0.99999)
                                mcy = max(0, min(s.NCY - 1, mcy))
                                mcx = int((xc - s.CB[0]) / s.CW + 0.99999)
                                mcx = max(0, min(s.NCX - 1, mcx))
                                mcsx = mcx - (l2 - 1)
                                mcsy = mcy - (l4 - 1)
                                mcs  = mcsy * (l3 - l2 + 1) + mcsx
                                if ks == 1:
                                    mcs += (s.LIMS[0, 2] - s.LIMS[0, 1] + 1) * \
                                           (s.LIMS[0, 4] - s.LIMS[0, 3] + 1)
                                mc2 = mcy * s.NCX + mcx
                                if isurf_val == 5:
                                    mc2 += (l1 - 1) * s.NCX * s.NCY
                                else:
                                    mc2 += (l1 - 2) * s.NCX * s.NCY
                                at = at * (z - zs) / dz
                                reflect3(s, n, ks, mcs, xc, yc, zs, mc2)
                                hit_surface = True
                                break

            if hit_surface:
                continue    # redo inner loop (molecule still moving)

            # --- outer boundary handling (Rob Nance's multi-boundary logic) ---
            ibound = 0
            icount = 0
            if x < s.CB[0] or x > s.CB[1]:
                ibound = 1;  icount += 1
            if y < s.CB[2] or y > s.CB[3]:
                ibound = 2;  icount += 1
            if z < s.CB[4] or z > s.CB[5]:
                ibound = 3;  icount += 1

            if icount > 1:
                dt3 = [5.0 * s.DTM] * 3
                if abs(s.PV[0, n]) > 1e-6:
                    dt1 = (s.CB[0] - s.PP[0, n]) / s.PV[0, n]
                    dt2 = (s.CB[1] - s.PP[0, n]) / s.PV[0, n]
                    dt3[0] = max(dt1, dt2)
                if abs(s.PV[1, n]) > 1e-6:
                    dt1 = (s.CB[2] - s.PP[1, n]) / s.PV[1, n]
                    dt2 = (s.CB[3] - s.PP[1, n]) / s.PV[1, n]
                    dt3[1] = max(dt1, dt2)
                if abs(s.PV[2, n]) > 1e-6:
                    dt1 = (s.CB[4] - s.PP[2, n]) / s.PV[2, n]
                    dt2 = (s.CB[5] - s.PP[2, n]) / s.PV[2, n]
                    dt3[2] = max(dt1, dt2)
                dtmin = 5.0 * s.DTM
                for kk in range(3):
                    if dt3[kk] < dtmin:
                        dtmin = dt3[kk]
                        ibound = kk + 1

            if ibound == 1:
                k_side = 0 if x < s.CB[0] else 1
                if s.IB[k_side] == 2:   # symmetry
                    at = at * (x - s.CB[k_side]) / dx
                    s.PP[0, n] = x - at * s.PV[0, n] + 0.001 * s.CW * (3.0 - 2.0 * (k_side + 1))
                    s.PP[1, n] = y - at * s.PV[1, n]
                    s.PP[2, n] = z - at * s.PV[2, n]
                    s.PV[0, n] = -s.PV[0, n]
                    continue
                else:
                    n = remove(s, n)
                    break

            if ibound == 2:
                k_side = 2 if y < s.CB[2] else 3
                if s.IB[k_side] == 2:
                    at = at * (y - s.CB[k_side]) / dy
                    s.PP[0, n] = x - at * s.PV[0, n]
                    s.PP[1, n] = y - at * s.PV[1, n] + 0.001 * s.CH * (7.0 - 2.0 * (k_side + 1))
                    s.PP[2, n] = z - at * s.PV[2, n]
                    s.PV[1, n] = -s.PV[1, n]
                    continue
                else:
                    n = remove(s, n)
                    break

            if ibound == 3:
                k_side = 4 if z < s.CB[4] else 5
                if s.IB[k_side] == 2:
                    at = at * (z - s.CB[k_side]) / dz
                    s.PP[0, n] = x - at * s.PV[0, n]
                    s.PP[1, n] = y - at * s.PV[1, n]
                    s.PP[2, n] = z - at * s.PV[2, n] + 0.001 * s.CD * (11.0 - 2.0 * (k_side + 1))
                    s.PV[2, n] = -s.PV[2, n]
                    continue
                else:
                    n = remove(s, n)
                    break

            # --- update cell assignment ---
            if (x < s.CG[0, mc] or x > s.CG[1, mc] or
                y < s.CG[2, mc] or y > s.CG[3, mc] or
                z < s.CG[4, mc] or z > s.CG[5, mc]):
                mcx = int((x - s.CB[0]) / s.CW + 0.99999)
                mcx = max(0, min(s.NCX - 1, mcx))
                mcy = int((y - s.CB[2]) / s.CH + 0.99999)
                mcy = max(0, min(s.NCY - 1, mcy))
                mcz = int((z - s.CB[4]) / s.CD + 0.99999)
                mcz = max(0, min(s.NCZ - 1, mcz))
                mc  = mcz * s.NCX * s.NCY + mcy * s.NCX + mcx

            mscx = int(((x - s.CG[0, mc]) / s.CW) * (s.NSCX - 0.001)) + 1
            mscy = int(((y - s.CG[2, mc]) / s.CH) * (s.NSCY - 0.001)) + 1
            mscz = int(((z - s.CG[4, mc]) / s.CD) * (s.NSCZ - 0.001)) + 1
            msc_new = ((mscz - 1) * s.NSCX * s.NSCY +
                       (mscy - 1) * s.NSCX + (mscx - 1) +
                       s.NSCX * s.NSCY * s.NSCZ * mc)
            msc_new = max(0, min(MNSC - 1, msc_new))
            s.IPL[n] = msc_new
            s.PP[0, n] = x
            s.PP[1, n] = y
            s.PP[2, n] = z
            break    # done with this molecule, move to next n

        else:
            # while-True fell through without break → shouldn't happen
            pass

        if ift < 0 and n >= s.NM:
            # all existing molecules processed → let entering molecules in
            ift = 1
            enter3(s)
            # Don't increment n; the entering molecules are appended at end

        n += 1

# ---------------------------------------------------------------------------
# ENTER3
# ---------------------------------------------------------------------------

def enter3(s: State):
    """Generate molecules entering at stream boundaries and from the jet."""

    for n_side in range(6):
        if s.IB[n_side] != 1:
            continue
        # determine sweep dimensions
        if n_side < 2:
            ncs1, ncs2 = s.NCY, s.NCZ
        elif n_side < 4:
            ncs1, ncs2 = s.NCX, s.NCZ
        else:
            ncs1, ncs2 = s.NCX, s.NCY

        for nc1 in range(1, ncs1 + 1):
            for nc2 in range(1, ncs2 + 1):
                for l in range(MNSP):
                    vmp = math.sqrt(2.0 * s.BOLTZ * s.FTMP / s.SP[4, l])
                    if n_side < 2:
                        a = s.BME[n_side, l] * s.CH * s.CD / (s.FH * s.FD) + s.BMR[n_side, l]
                    elif n_side < 4:
                        a = s.BME[n_side, l] * s.CW * s.CD / (s.FW * s.FD) + s.BMR[n_side, l]
                    else:
                        a = s.BME[n_side, l] * s.CW * s.CH / (s.FW * s.FH) + s.BMR[n_side, l]
                    m_count = int(a)
                    s.BMR[n_side, l] = a - m_count

                    if m_count <= 0:
                        continue

                    # speed ratio for inward normal component
                    sc = 0.0
                    has_drift = False
                    if n_side < 2 and abs(s.VFX) > 1e-6:
                        sc = s.VFX / vmp if n_side == 0 else -s.VFX / vmp
                        has_drift = True
                    elif 1 < n_side < 4 and abs(s.VFY) > 1e-6:
                        sc = s.VFY / vmp if n_side == 2 else -s.VFY / vmp
                        has_drift = True
                    elif n_side > 3 and abs(s.VFZ) > 1e-6:
                        sc = s.VFZ / vmp if n_side == 4 else -s.VFZ / vmp
                        has_drift = True

                    fs1 = sc + math.sqrt(sc * sc + 2.0)
                    fs2 = 0.5 * (1.0 + sc * (2.0 * sc - fs1))

                    # determine cell mc (0-based)
                    if n_side == 0:
                        mc = (nc2 - 1) * s.NCX * s.NCY + (nc1 - 1) * s.NCX
                    elif n_side == 1:
                        mc = (nc2 - 1) * s.NCX * s.NCY + nc1 * s.NCX - 1
                    elif n_side == 2:
                        mc = (nc2 - 1) * s.NCX * s.NCY + (nc1 - 1)
                    elif n_side == 3:
                        mc = (nc2 - 1) * s.NCX * s.NCY + (s.NCY - 1) * s.NCX + (nc1 - 1)
                    elif n_side == 4:
                        mc = (nc2 - 1) * s.NCX + (nc1 - 1)
                    else:
                        mc = (s.NCZ - 1) * s.NCX * s.NCY + (nc2 - 1) * s.NCX + (nc1 - 1)
                    mc = max(0, min(MNC - 1, mc))

                    for _ in range(m_count):
                        if s.NM >= MNM:
                            print(" WARNING: EXCESS MOLECULE LIMIT - RESTART WITH INCREASED FNUM")
                            break
                        ni = s.NM
                        s.NM += 1

                        # inward normal component
                        if has_drift:
                            qa = 3.0
                            if sc < -3.0: qa = abs(sc) + 1.0
                            while True:
                                u  = -qa + 2.0 * qa * rf()
                                un = u + sc
                                if un < 0.0: continue
                                acc = (2.0 * un / fs1) * math.exp(fs2 - u * u)
                                if acc >= rf(): break
                            inward = un * vmp
                        else:
                            inward = math.sqrt(-math.log(rf())) * vmp

                        # two tangential components
                        tang1, tang2 = rvelc(vmp)

                        # assign velocity components
                        if n_side == 0:
                            s.PV[0, ni] =  inward
                            s.PV[1, ni] = tang1 + s.VFY
                            s.PV[2, ni] = tang2 + s.VFZ
                        elif n_side == 1:
                            s.PV[0, ni] = -inward
                            s.PV[1, ni] = tang1 + s.VFY
                            s.PV[2, ni] = tang2 + s.VFZ
                        elif n_side == 2:
                            s.PV[1, ni] =  inward
                            s.PV[0, ni] = tang1 + s.VFX
                            s.PV[2, ni] = tang2 + s.VFZ
                        elif n_side == 3:
                            s.PV[1, ni] = -inward
                            s.PV[0, ni] = tang1 + s.VFX
                            s.PV[2, ni] = tang2 + s.VFZ
                        elif n_side == 4:
                            s.PV[2, ni] =  inward
                            s.PV[0, ni] = tang1 + s.VFX
                            s.PV[1, ni] = tang2 + s.VFY
                        else:
                            s.PV[2, ni] = -inward
                            s.PV[0, ni] = tang1 + s.VFX
                            s.PV[1, ni] = tang2 + s.VFY

                        if s.ISPR[0, l] > 0:
                            s.PR[ni] = srot(s.FTMP, s.ISPR[0, l])

                        # position just inside boundary
                        if   n_side == 0: s.PP[0, ni] = s.CB[0] + 0.001 * s.CW
                        elif n_side == 1: s.PP[0, ni] = s.CB[1] - 0.001 * s.CW
                        elif n_side == 2: s.PP[1, ni] = s.CB[2] + 0.001 * s.CH
                        elif n_side == 3: s.PP[1, ni] = s.CB[3] - 0.001 * s.CH
                        elif n_side == 4: s.PP[2, ni] = s.CB[4] + 0.001 * s.CD
                        else:             s.PP[2, ni] = s.CB[5] - 0.001 * s.CD

                        # transverse positions
                        if n_side < 2:
                            s.PP[1, ni] = s.CG[2, mc] + rf() * s.CH
                            s.PP[2, ni] = s.CG[4, mc] + rf() * s.CD
                        elif n_side < 4:
                            s.PP[0, ni] = s.CG[0, mc] + rf() * s.CW
                            s.PP[2, ni] = s.CG[4, mc] + rf() * s.CD
                        else:
                            s.PP[0, ni] = s.CG[0, mc] + rf() * s.CW
                            s.PP[1, ni] = s.CG[2, mc] + rf() * s.CH

                        if MNSP > 1:
                            s.IPS[ni] = l

                        # sub-cell
                        mscx = int(((s.PP[0, ni] - s.CG[0, mc]) / s.CW) * (s.NSCX - 0.001)) + 1
                        mscy = int(((s.PP[1, ni] - s.CG[2, mc]) / s.CH) * (s.NSCY - 0.001)) + 1
                        mscz = int(((s.PP[2, ni] - s.CG[4, mc]) / s.CD) * (s.NSCZ - 0.001)) + 1
                        msc  = ((mscz - 1) * s.NSCX * s.NSCY +
                                (mscy - 1) * s.NSCX + (mscx - 1) +
                                s.NSCX * s.NSCY * s.NSCZ * mc)
                        s.IPL[ni] = max(0, min(MNSC - 1, msc))

    # --- jet ---
    if s.IJET > 0:
        for l in range(MNSP):
            vmp = math.sqrt(2.0 * s.BOLTZ * s.TMPJ / s.SP[4, l])
            a = s.BMEJ[l] + s.BMRJ[l]
            m_count = int(math.sqrt(a))
            s.BMRJ[l] = a - m_count * m_count

            if m_count <= 0:
                continue

            sc = s.FVJ / vmp if abs(s.FVJ) > 1e-6 else 0.0
            fs1 = sc + math.sqrt(sc * sc + 2.0)
            fs2 = 0.5 * (1.0 + sc * (2.0 * sc - fs1))

            for k_idx in range(1, m_count + 1):
                for kk_idx in range(1, m_count + 1):
                    if s.NM >= MNM:
                        print(" WARNING: EXCESS MOLECULE LIMIT - RESTART WITH INCREASED FNUM")
                        break
                    ni = s.NM
                    s.NM += 1

                    if abs(s.FVJ) > 1e-6:
                        qa = 3.0
                        if sc < -3.0: qa = abs(sc) + 1.0
                        while True:
                            u  = -qa + 2.0 * qa * rf()
                            un = u + sc
                            if un < 0.0: continue
                            acc = (2.0 * un / fs1) * math.exp(fs2 - u * u)
                            if acc >= rf(): break
                        s.PV[1, ni] = un * vmp
                    else:
                        s.PV[1, ni] = math.sqrt(-math.log(rf())) * vmp

                    tang1, tang2 = rvelc(vmp)
                    s.PV[0, ni] = tang1
                    s.PV[2, ni] = tang2

                    if s.ISPR[0, l] > 0:
                        s.PR[ni] = srot(s.TMPJ, s.ISPR[0, l])

                    s.PP[1, ni] = 0.001 * s.CH
                    s.IPS[ni]   = l

                    r_rad = math.sqrt((k_idx - rf()) / m_count) * s.RJ
                    azim  = 2.0 * s.PI * (kk_idx - rf()) / m_count
                    if s.IJET == 2: azim *= 0.5
                    if s.IJET == 3: azim *= 0.25

                    s.PP[0, ni] = s.XJ + r_rad * math.cos(azim)
                    s.PP[2, ni] = s.ZJ + r_rad * math.sin(azim)

                    mcx = int((s.PP[0, ni] - s.CB[0]) / s.CW + 0.99999)
                    mcx = max(0, min(s.NCX - 1, mcx))
                    mcz = int((s.PP[2, ni] - s.CB[4]) / s.CD + 0.99999)
                    mcz = max(0, min(s.NCZ - 1, mcz))
                    mc  = mcz * s.NCX * s.NCY + mcx

                    mscx = int(((s.PP[0, ni] - s.CG[0, mc]) / s.CW) * (s.NSCX - 0.001)) + 1
                    mscz = int(((s.PP[2, ni] - s.CG[4, mc]) / s.CD) * (s.NSCZ - 0.001)) + 1
                    msc  = ((mscz - 1) * s.NSCX * s.NSCY + (mscx - 1) +
                            s.NSCX * s.NSCY * s.NSCZ * mc)
                    s.IPL[ni] = max(0, min(MNSC - 1, msc))

# ---------------------------------------------------------------------------
# INDEXM
# ---------------------------------------------------------------------------

def indexm(s: State):
    """
    Build the cross-reference array IR so that molecules are ordered
    by group → cell → sub-cell.  Mirrors INDEXM.FOR exactly.
    """
    s.IG[1, :] = 0
    s.IC[1, :, :] = 0
    s.ISCG[1, :, :] = 0

    for n in range(s.NM):
        ls = s.IPS[n] if MNSP > 1 else 0
        mg = s.ISP[ls]       # 0-based group
        s.IG[1, mg] += 1
        msc = s.IPL[n]
        s.ISCG[1, msc, mg] += 1
        mc  = s.ISC[msc]
        s.IC[1, mc, mg] += 1

    # set start addresses
    m_addr = 0
    for l in range(MNSG):
        s.IG[0, l] = m_addr
        m_addr += s.IG[1, l]

    for l in range(MNSG):
        m_addr = s.IG[0, l]
        for n in range(MNC):
            s.IC[0, n, l] = m_addr
            m_addr += s.IC[1, n, l]

        m_addr = s.IG[0, l]
        for n in range(MNSC):
            s.ISCG[0, n, l] = m_addr
            m_addr += s.ISCG[1, n, l]
            s.ISCG[1, n, l] = 0

    # fill cross-reference array IR
    for n in range(s.NM):
        ls = s.IPS[n] if MNSP > 1 else 0
        mg = s.ISP[ls]
        msc = s.IPL[n]
        s.ISCG[1, msc, mg] += 1
        k = s.ISCG[0, msc, mg] + s.ISCG[1, msc, mg] - 1
        s.IR[k] = n

# ---------------------------------------------------------------------------
# SELECT  (collision pair selection)
# ---------------------------------------------------------------------------

def select_pair(s: State):
    """
    Select a collision pair and compute CVR = sigma_T * v_r.
    Results stored in s.L, s.M, s.LS, s.MS, s.VRC, s.VRR, s.VR, s.CVR.
    Uses 0-based indices throughout.
    """
    n  = s.N
    nn = s.NN
    mm = s.MM

    # first molecule from group NN in cell N
    cnt = s.IC[1, n, nn]
    k = int(rf() * (cnt - 0.001)) + s.IC[0, n, nn]
    s.L = s.IR[k]

    while True:
        msc = s.IPL[s.L]
        # find nearest sub-cell that has a group-MM molecule
        if (nn == mm and s.ISCG[1, msc, mm] == 1) or \
           (nn != mm and s.ISCG[1, msc, mm] == 0):
            nst, nsg = 1, 1
            found = False
            for _ in range(MNSC * 2):
                inc  = nsg * nst
                nsg  = -nsg
                nst += 1
                msc += inc
                if msc < 0 or msc >= MNSC: continue
                if s.ISC[msc] != n: continue
                if s.ISCG[1, msc, mm] >= 1:
                    found = True
                    break
            if not found:
                break  # no partner found; skip

        cnt2 = s.ISCG[1, msc, mm]
        k = int(rf() * (cnt2 - 0.001)) + s.ISCG[0, msc, mm]
        s.M = s.IR[k]
        if s.L == s.M:
            continue    # re-pick
        break

    s.VRC[:] = s.PV[:, s.L] - s.PV[:, s.M]
    s.VRR = float(np.dot(s.VRC, s.VRC))
    s.VR  = math.sqrt(s.VRR)

    ls = s.IPS[s.L] if MNSP > 1 else 0
    ms = s.IPS[s.M] if MNSP > 1 else 0
    s.LS = ls
    s.MS = ms

    # collision cross-section × relative speed  eqn (4.63)
    s.CVR = (s.VR * s.SPM[0, ls, ms] *
             ((2.0 * s.BOLTZ * s.SPM[1, ls, ms] /
               (s.SPM[4, ls, ms] * s.VRR)) **
              (s.SPM[2, ls, ms] - 0.5)) /
             s.SPM[5, ls, ms])

# ---------------------------------------------------------------------------
# ELASTIC
# ---------------------------------------------------------------------------

def elastic(s: State):
    """
    Generate post-collision velocities using VHS or VSS model.
    Mirrors ELASTIC.FOR.
    """
    ls, ms = s.LS, s.MS
    rml = s.SPM[4, ls, ms] / s.SP[4, ms]
    rmm = s.SPM[4, ls, ms] / s.SP[4, ls]

    vccm = rml * s.PV[:, s.L] + rmm * s.PV[:, s.M]

    vrcp = np.empty(3)
    if abs(s.SPM[3, ls, ms] - 1.0) < 1e-3:
        # VHS — isotropic scattering
        b = 2.0 * rf() - 1.0
        a = math.sqrt(1.0 - b * b)
        c = 2.0 * s.PI * rf()
        vrcp[0] = b * s.VR
        vrcp[1] = a * math.cos(c) * s.VR
        vrcp[2] = a * math.sin(c) * s.VR
    else:
        # VSS  eqn (2.22)
        b = 2.0 * (rf() ** s.SPM[3, ls, ms]) - 1.0
        a = math.sqrt(1.0 - b * b)
        c = 2.0 * s.PI * rf()
        oc, sc2 = math.cos(c), math.sin(c)
        d = math.sqrt(s.VRC[1] ** 2 + s.VRC[2] ** 2)
        if d > 1e-6:
            vrcp[0] = b * s.VRC[0] + a * sc2 * d
            vrcp[1] = b * s.VRC[1] + a * (s.VR * s.VRC[2] * oc - s.VRC[0] * s.VRC[1] * sc2) / d
            vrcp[2] = b * s.VRC[2] - a * (s.VR * s.VRC[1] * oc + s.VRC[0] * s.VRC[2] * sc2) / d
        else:
            vrcp[0] = b * s.VRC[0]
            vrcp[1] = a * oc * s.VRC[0]
            vrcp[2] = a * sc2 * s.VRC[0]

    s.PV[:, s.L] = vccm + vrcp * rmm
    s.PV[:, s.M] = vccm - vrcp * rml

# ---------------------------------------------------------------------------
# INELR  — rotational energy redistribution
# ---------------------------------------------------------------------------

def inelr(s: State):
    """
    Larsen-Borgnakke redistribution of rotational energy.
    Mirrors INELR.FOR.
    """
    ls, ms = s.LS, s.MS
    eti = 0.5 * s.SPM[4, ls, ms] * s.VRR
    eci = 0.0
    ecf = 0.0
    ecc = eti
    xib = 2.5 - s.SPM[2, ls, ms]
    irt = 0
    ir_flag = [0, 0]

    mols = [s.L, s.M]
    species = [ls, ms]
    partner = [ms, ls]

    for nsp in range(2):
        k_mol = mols[nsp]
        ks    = species[nsp]
        js    = partner[nsp]
        ir_flag[nsp] = 0
        if s.ISPR[0, ks] > 0:
            if s.ISPR[1, ks] == 0:
                atk = 1.0 / s.SPR[0, ks, js]
            else:
                atk = 1.0 / (s.SPR[0, ks, js] +
                              s.SPR[1, ks, js] * s.CT[s.N] +
                              s.SPR[2, ks, js] * s.CT[s.N] ** 2)
            if atk > rf():
                irt = 1
                ir_flag[nsp] = 1
                ecc += s.PR[k_mol]
                eci += s.PR[k_mol]
                xib += 0.5 * s.ISPR[0, ks]

    if irt == 1:
        for nsp in range(2):
            if ir_flag[nsp] == 1:
                k_mol = mols[nsp]
                ks    = species[nsp]
                xib  -= 0.5 * s.ISPR[0, ks]
                if s.ISPR[0, ks] == 2:
                    erm = 1.0 - rf() ** (1.0 / xib)
                else:
                    xia = 0.5 * s.ISPR[0, ks]
                    erm = lbs(xia - 1.0, xib - 1.0)
                s.PR[k_mol] = erm * ecc
                ecc -= s.PR[k_mol]
                ecf += s.PR[k_mol]

        etf = eti + eci - ecf
        a = math.sqrt(2.0 * etf / s.SPM[4, ls, ms])
        if abs(s.SPM[3, ls, ms] - 1.0) < 1e-3:
            s.VR = a
        else:
            s.VRC *= a / s.VR
            s.VR   = a

# ---------------------------------------------------------------------------
# COLLMR  — collision routine
# ---------------------------------------------------------------------------

def collmr(s: State):
    """
    Perform NTC collisions in all cells.  Mirrors COLLMR.FOR.
    """
    for n in range(MNC):
        s.N = n
        for nn in range(MNSG):
            s.NN = nn
            for mm in range(MNSG):
                s.MM = mm
                # average number of group-MM molecules
                sn = 0.0
                for k in range(MNSP):
                    if s.ISP[k] == mm:
                        sn += s.CS[0, n, k]
                if sn > 1.0:
                    avn = sn / float(s.NSMP) if s.NSMP > 0 else sn
                else:
                    avn = float(s.IC[1, n, mm])

                asel = (0.5 * s.IC[1, n, nn] * avn * s.FNUM *
                        s.CCG[0, n, nn, mm] * s.DTM / s.CC +
                        s.CCG[1, n, nn, mm])
                nsel = int(asel)
                s.CCG[1, n, nn, mm] = asel - nsel

                if nsel <= 0:
                    continue

                insufficient = ((nn != mm and
                                 (s.IC[1, n, nn] < 1 or s.IC[1, n, mm] < 1)) or
                                (nn == mm and s.IC[1, n, nn] < 2))
                if insufficient:
                    s.CCG[1, n, nn, mm] += nsel
                    continue

                cvm = s.CCG[0, n, nn, mm]
                s.SELT += nsel

                for _ in range(nsel):
                    select_pair(s)
                    if s.CVR > cvm:
                        cvm = s.CVR
                    if rf() < s.CVR / s.CCG[0, n, nn, mm]:
                        s.NCOL += 1.0
                        s.SEPT += math.sqrt(
                            (s.PP[0, s.L] - s.PP[0, s.M]) ** 2 +
                            (s.PP[1, s.L] - s.PP[1, s.M]) ** 2 +
                            (s.PP[2, s.L] - s.PP[2, s.M]) ** 2)
                        s.COL[s.LS, s.MS] += 1.0
                        s.COL[s.MS, s.LS] += 1.0

                        if s.ISPR[0, s.LS] > 0 or s.ISPR[0, s.MS] > 0:
                            inelr(s)
                        elastic(s)

                s.CCG[0, n, nn, mm] = cvm

# ---------------------------------------------------------------------------
# SAMPI3  — initialise sampling
# ---------------------------------------------------------------------------

def sampi3(s: State):
    """Reset all sampling accumulators.  Mirrors SAMPI3.FOR."""
    s.NSMP = 0
    s.TIMI = s.TIME
    for l in range(MNSP):
        for n in range(MNC):
            s.CS[0, n, l] = 1e-6
            s.CS[1:, n, l] = 0.0
            s.CSR[n, l] = 0.0
        for n in range(MNSE):
            s.CSS[0, n, l] = 1e-6
            s.ICS[n] = 0
            s.CSS[1:, n, l] = 0.0

# ---------------------------------------------------------------------------
# SAMPLE3  — accumulate flow-field samples
# ---------------------------------------------------------------------------

def sample3(s: State):
    """Sample molecules into CS accumulators.  Mirrors SAMPLE3.FOR."""
    s.NSMP += 1
    for nn in range(MNSG):
        for n in range(MNC):
            count = s.IC[1, n, nn]
            if count > 0:
                start = s.IC[0, n, nn]
                for j in range(count):
                    k = start + j
                    mol = s.IR[k]
                    i = s.IPS[mol] if MNSP > 1 else 0
                    s.CS[0, n, i] += 1.0
                    for ll in range(3):
                        s.CS[ll + 1, n, i] += s.PV[ll, mol]
                        s.CS[ll + 4, n, i] += s.PV[ll, mol] ** 2
                    if MNMR > 1:
                        s.CSR[n, i] += s.PR[mol]

# ---------------------------------------------------------------------------
# OUT3  — output results
# ---------------------------------------------------------------------------

def out3(s: State):
    """Write flow-field and surface results to DSMC3.OUT.  Mirrors OUT3.FOR."""
    with open('DSMC3.OUT', 'w') as f:
        f.write(f" FLOW SAMPLED FROM TIME {s.TIMI:.6e} TO TIME {s.TIME:.6e}\n")
        f.write(" COLLISIONS:-\n")
        for m in range(MNSP):
            row = "  ".join(f"{s.COL[m, l]:14.0f}" for l in range(MNSP))
            f.write(row + "\n")
        f.write(f" TOTAL NUMBER OF SAMPLES {s.NSMP}\n")
        f.write(f" {s.NM} MOLECULES\n")
        f.write(f" {s.MOVT:.0f} TOTAL MOLECULAR MOVES\n")
        if s.NCOL > 0:
            f.write(f" {int(s.SELT)} SELECTIONS  {int(s.NCOL)} COLLISION EVENTS"
                    f"  RATIO {s.NCOL / s.SELT:.6f}\n")
            f.write(f" MEAN COLLISION SEPARATION {s.SEPT / s.NCOL:.6e}\n")

        f.write("\n")
        for ks in range(2):
            if s.ISURF[ks] == 0:
                continue
            f.write(f" SURFACE {ks + 1}\n\n")
            nel = ((s.LIMS[ks, 2] - s.LIMS[ks, 1] + 1) *
                   (s.LIMS[ks, 4] - s.LIMS[ks, 3] + 1))
            if ks == 0:
                nel1, nel2 = 0, nel - 1
            else:
                off = ((s.LIMS[0, 2] - s.LIMS[0, 1] + 1) *
                       (s.LIMS[0, 4] - s.LIMS[0, 3] + 1))
                nel1 = off
                nel2 = off + nel - 1

            dt_inv = s.FNUM / (s.TIME - s.TIMI) if (s.TIME - s.TIMI) > 0 else 0.0

            f.write("    X COORD     Y COORD      Z COORD     SAMPLE"
                    "     FRACTION SPECIES 1, SPECIES 2....\n")
            for k in range(nel1, nel2 + 1):
                nc = s.ICS[k] - 1   # back to 0-based
                if nc < 0: continue
                isurf_val = s.ISURF[ks]
                if isurf_val < 3:
                    y_c = (s.LIMS[ks, 0] - 1) * s.CH + s.CB[2]
                    x_c = 0.5 * (s.CG[0, nc] + s.CG[1, nc])
                    z_c = 0.5 * (s.CG[4, nc] + s.CG[5, nc])
                elif isurf_val < 5:
                    x_c = (s.LIMS[ks, 0] - 1) * s.CW + s.CB[0]
                    y_c = 0.5 * (s.CG[2, nc] + s.CG[3, nc])
                    z_c = 0.5 * (s.CG[4, nc] + s.CG[5, nc])
                else:
                    z_c = (s.LIMS[ks, 0] - 1) * s.CD + s.CB[4]
                    y_c = 0.5 * (s.CG[2, nc] + s.CG[3, nc])
                    x_c = 0.5 * (s.CG[0, nc] + s.CG[1, nc])
                ss1 = sum(s.CSS[0, k, l] for l in range(MNSP))
                fracs = "  ".join(f"{s.CSS[0, k, l] / ss1:13.6f}" for l in range(MNSP))
                f.write(f"  {x_c:12.5f}  {y_c:12.5f}  {z_c:12.5f}  {ss1:12.1f}  {fracs}\n")

            f.write("     X COORD      Y COORD     Z COORD     NUM FLUX"
                    "    INC PRESS  REFL PRESS  INC SH1  REFL SH1"
                    "  INC SH2  REFL SH2  INC TR EN  REFL TR EN"
                    "  INC ROT EN  REFL ROT EN  NET HEAT FLUX\n")
            for k in range(nel1, nel2 + 1):
                nc = s.ICS[k] - 1
                if nc < 0: continue
                isurf_val = s.ISURF[ks]
                if isurf_val < 3:
                    y_c  = (s.LIMS[ks, 0] - 1) * s.CH + s.CB[2]
                    x_c  = 0.5 * (s.CG[0, nc] + s.CG[1, nc])
                    z_c  = 0.5 * (s.CG[4, nc] + s.CG[5, nc])
                    ar   = s.CW * s.CD
                elif isurf_val < 5:
                    x_c  = (s.LIMS[ks, 0] - 1) * s.CW + s.CB[0]
                    y_c  = 0.5 * (s.CG[2, nc] + s.CG[3, nc])
                    z_c  = 0.5 * (s.CG[4, nc] + s.CG[5, nc])
                    ar   = s.CH * s.CD
                else:
                    z_c  = (s.LIMS[ks, 0] - 1) * s.CD + s.CB[4]
                    y_c  = 0.5 * (s.CG[2, nc] + s.CG[3, nc])
                    x_c  = 0.5 * (s.CG[0, nc] + s.CG[1, nc])
                    ar   = s.CW * s.CH
                ss = np.sum(s.CSS[:, k, :], axis=1)   # sum over species
                ss *= dt_inv / ar
                f.write(f"  {x_c:13.5e}  {y_c:13.5e}  {z_c:13.5e}"
                        + "".join(f"  {ss[i]:13.5e}" for i in
                                  [0, 1, 2, 3, 8, 9, 10, 4, 5, 6, 7])
                        + f"  {ss[4]+ss[5]+ss[6]+ss[7]:13.5e}\n")

        # --- flow-field ---
        f.write(" FLOWFIELD PROPERTIES\n")
        f.write(" SAMPLES\n CELL     N SP 1    N SP 2     ETC\n")
        for n in range(MNC):
            vals = "  ".join(f"{s.CS[0, n, l]:12.0f}" for l in range(MNSP))
            f.write(f"  {n+1}  {vals}\n")

        f.write(" FLOWFIELD PROPERTIES\n")
        f.write("  CELL   X COORD   Y COORD   Z COORD   DENSITY"
                "   TR TEMP   ROT TEMP    OV TEMP      U         V         W\n")

        svel = np.zeros((3, MNC))
        fac  = s.FNUM / (s.CC * s.NSMP) if s.NSMP > 0 else 0.0

        for n in range(MNC):
            sn   = 0.0; sm = 0.0
            smu  = np.zeros(3)
            smcc = 0.0; sre = 0.0; srdf = 0.0

            for l in range(MNSP):
                sn   += s.CS[0, n, l]
                sm   += s.SP[4, l] * s.CS[0, n, l]
                for k in range(3):
                    smu[k] += s.SP[4, l] * s.CS[k+1, n, l]
                smcc += (s.CS[4, n, l] + s.CS[5, n, l] + s.CS[6, n, l]) * s.SP[4, l]
                sre  += s.CSR[n, l]
                srdf += s.ISPR[0, l] * s.CS[0, n, l]

            if sn < 1e-10:
                continue
            denn = sn * fac
            den  = denn * sm / sn
            vel  = smu / sm
            svel[:, n] = vel
            uu   = float(np.dot(vel, vel))
            tt   = (smcc - sm * uu) / (3.0 * s.BOLTZ * sn)
            trot = (2.0 / s.BOLTZ) * sre / srdf if srdf > 1e-6 else 0.0
            temp = (3.0 * tt + (srdf / sn) * trot) / (3.0 + srdf / sn) if srdf > 1e-6 else tt
            s.CT[n] = temp
            xc = 0.5 * (s.CG[0, n] + s.CG[1, n])
            yc = 0.5 * (s.CG[2, n] + s.CG[3, n])
            zc = 0.5 * (s.CG[4, n] + s.CG[5, n])
            f.write(f"  {n+1:5d}  {xc:9.5f}  {yc:9.5f}  {zc:9.5f}"
                    f"  {den:.4e}  {tt:9.4f}  {trot:9.4f}  {temp:9.4f}"
                    f"  {vel[0]:9.4f}  {vel[1]:9.4f}  {vel[2]:9.4f}\n")

        for l in range(MNSP):
            f.write(f" SPECIES {l+1}\n")
            f.write("  CELL   X COORD    Y COORD    Z COORD   N DENS"
                    "    DENSITY    TTX    TTY    TTZ   TR TEMP"
                    "   ROT TEMP    TEMP    U DIF   V DIF   W DIF\n")
            for n in range(MNC):
                if s.CS[0, n, l] < 1e-10:
                    continue
                denn = s.CS[0, n, l] * fac
                den  = s.SP[4, l] * denn
                vel  = s.CS[1:4, n, l] / s.CS[0, n, l]
                uu   = float(np.dot(vel, vel))
                ttx  = (s.SP[4, l] / s.BOLTZ) * (s.CS[4, n, l] / s.CS[0, n, l] - vel[0] ** 2)
                tty  = (s.SP[4, l] / s.BOLTZ) * (s.CS[5, n, l] / s.CS[0, n, l] - vel[1] ** 2)
                ttz  = (s.SP[4, l] / s.BOLTZ) * (s.CS[6, n, l] / s.CS[0, n, l] - vel[2] ** 2)
                tt   = (s.SP[4, l] / (3.0 * s.BOLTZ)) * (
                        (s.CS[4, n, l] + s.CS[5, n, l] + s.CS[6, n, l]) / s.CS[0, n, l] - uu)
                if s.ISPR[0, l] > 0:
                    trot = 2.0 * s.CSR[n, l] / (s.ISPR[0, l] * s.BOLTZ * s.CS[0, n, l])
                else:
                    trot = 0.0
                temp = (3.0 * tt + s.ISPR[0, l] * trot) / (3.0 + s.ISPR[0, l])
                diff_vel = vel - svel[:, n]
                xc = 0.5 * (s.CG[0, n] + s.CG[1, n])
                yc = 0.5 * (s.CG[2, n] + s.CG[3, n])
                zc = 0.5 * (s.CG[4, n] + s.CG[5, n])
                f.write(f"  {n+1:5d}  {xc:9.5f}  {yc:9.5f}  {zc:9.5f}"
                        f"  {denn:.4e}  {den:.4e}"
                        f"  {ttx:9.4f}  {tty:9.4f}  {ttz:9.4f}"
                        f"  {tt:9.4f}  {trot:9.4f}  {temp:9.4f}"
                        f"  {diff_vel[0]:9.4f}  {diff_vel[1]:9.4f}  {diff_vel[2]:9.4f}\n")

# ---------------------------------------------------------------------------
# Restart  I/O
# ---------------------------------------------------------------------------

def write_restart(s: State):
    with open('DSMC3.RES', 'wb') as f:
        pickle.dump(s, f, protocol=pickle.HIGHEST_PROTOCOL)
    print("  Restart file written.")

def read_restart():
    with open('DSMC3.RES', 'rb') as f:
        s = pickle.load(f)
    print("  Restart file loaded.")
    return s

# ---------------------------------------------------------------------------
# MAIN  — mirrors the DSMC3 program unit
# ---------------------------------------------------------------------------

def main():
    nql  = int(input(" INPUT 0,1 FOR CONTINUING,NEW CALCULATION: "))
    nqls = int(input(" INPUT 0,1 FOR CONTINUING,NEW SAMPLE: "))

    if nql == 1:
        s = State()
        init3(s)
    else:
        s = read_restart()

    if nqls == 1:
        sampi3(s)

    while True:
        s.NPR += 1

        if s.NPR <= s.NPS:
            sampi3(s)

        for jjj in range(s.NSP):
            for iii in range(s.NIS):
                s.TIME += s.DTM
                print(f" DSMC3:- Move {iii+1:5d}{jjj+1:5d} of {s.NIS:5d}{s.NSP:5d}"
                      f"  {s.NM:8d} Mols  {s.NCOL:14.0f} Colls")
                move3(s)
                indexm(s)
                collmr(s)

            sample3(s)

        print(f" WRITING RESTART AND OUTPUT FILES  {s.NPR}  OF  {s.NPT}")
        write_restart(s)
        out3(s)

        if s.NPR >= s.NPT:
            break

    print(" DONE.")

# ---------------------------------------------------------------------------

if __name__ == '__main__':
    main()
