%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%    An Introduction to Scientific Computing          %%%%%%%
%%%%%%%    I. Danaila, P. Joly, S. M. Kaber & M. Postel     %%%%%%%
%%%%%%%                 Springer, 2005                      %%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%=====================================
% Complete algorithm (direct problem)
% to compute the final temperature field
%========================================
if(ifirst==0 | ichange==1)
                              updatej('Computation of the matrix of the system ...please wait');
[A,Fo]=CalcA(K,Irefd,TD,Ireft);    % Matrix of the system
                              updatej('...matrix of the system OK');
                              updatej(' ***********************')

                              updatej('Computation of the (homogeneous) field  without resistances ...');
T0=A\Fo;                    % Problem without resistances
                              updatej('The temperature field without resistances is displayed ...');
                              updatej(' ***********************')
                              updatej('===> Click on "Next" to continue the computation');
                              updatej(' ***********************')
ifirst=1;ichange=0;              % optimization to calculate A only once
else
                              updatej('===> We have the same (homogeneous) field  without resistances ...');
                              updatej('===> Click on "Next" to continue the computation');
                              updatej(' ***********************')

end

kbpl=1;
if(exist('Tr')==1);clear Tr;end;  % temp fields for the resistances are cleared

%Interp_P1(U,21,2);
figure(fg2);colormap('default');
trisurf(I123,XYs(:,1),XYs(:,2),zeros(Ns,1),T0); view(2);shading interp
hold on;Show_border(xb,yb,fg2);hold off;title('Homogeneous temperature','FontSize',txtH);


bisos= uicontrol('Parent',fg2, ...
	'Units','pixels', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
   'Callback',['updatej([''Computes '' num2str(nisol) '' iso-lines'']);'...
               'Interp_mouse(T0,nisol,fg2);hold on;Show_border(xb,yb,fg2);hold off;title(''Homogeneous temperature'',''FontSize'',txtH);'], ...
	'FontSize',txtH, ...
	'ForegroundColor',[0.75 0 0], ...
	'Position',[(frmW-2*butW)/9*5+butW 2 butW butH], ...
	'String','Iso-lines', ...
	'Tag','Pushbuttonc');



% Calcul des champs associes aux resistances

bpl= uicontrol('Parent',fg2, ...
	'Units','pixels', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
   'Callback',['if(kbpl <= NbR);'...
               ' updatej([''Computes the temp field of resistance  '' num2str(kbpl)]);'...   
               ' F=CalcF(XYr(kbpl,:),Rr,RU);Tr(:,kbpl)=A\F;'...
               ' figure(fg2);trisurf(I123,XYs(:,1),XYs(:,2),zeros(Ns,1),F);title([''Temp Resistance  '' num2str(kbpl)],''FontSize'',txtH);'...
               ' view(2);shading interp;hold on;Show_border(xb,yb,fg2);hold off;'...
                ' updatej(''===> Click on "Next"  '' );'...                 
               ' set(bisos,''Callback'', ''updatej([''''Computes '''' num2str(nisol) '''' iso-lines'''']);Interp_mouse(Tr(:,kbpl-1),nisol,fg2);hold on;Show_border(xb,yb,fg2);hold off;title([''''Temp Resistance  '''' num2str(kbpl-1)],''''FontSize'''',txtH);'');' ...
               'else;'...
                  'delete(bpl);updatej(''***********************'');updatej(''Superposition of the fields'');updatej(''===> You may modify the values of the resistances in the "Command panel"'' );updatej(''===>  Click then on "Validate"  '' );Superpose;'...   
               'end;'...
               'kbpl=kbpl+1;'], ...
	'FontSize',txtH, ...
	'ForegroundColor',[0.75 0 0], ...
	'Position',[(frmW-2*butW)/9*4 2 butW butH], ...
	'String','Next', ...
	'Tag','Pushbuttonc');




