%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%    An Introduction to Scientific Computing          %%%%%%%
%%%%%%%    I. Danaila, P. Joly, S. M. Kaber & M. Postel     %%%%%%%
%%%%%%%                 Springer, 2005                      %%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%====================================
% Visualization window
%====================================

if(icallv > 0)
   close(fg2)
else
   xPos=frmPos(1)+frmW+betwM;
   frmH=(frmH-2*topM)*0.9;
   frmW=frmH*1.25;
   yPos=frmPos(2)+frmPos(4)-frmH-topM;
   frmPos=[xPos yPos frmW frmH];
      txtH=frmH/35;butB=2*txtH;
   	butW=8*txtH;butH=1.6*txtH;

   axPos=[2*butB+butW butH+butB frmW-butW-3*butB frmH-butH-2*butB];
end

fg2 = figure('Units','pixels',...
   'NumberTitle','off',...
   'Name','Visu',...
   'Position',frmPos);

b = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','text',...
   'Position',[1 frmH-butB-2*butH butW 2*butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',[0.75 0.4 0.1],...
   'String',char('Print:',' fic.(eps)'));

dyp = uicontrol('Units','pixels',...
   'Parent',fg2,...
   'Style','edit',...
   'Position',[1 frmH-butB-2*butH-txtH butW butH],...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'BackgroundColor',[1 1 1],...
   'String','fic',...
   'Callback',['figure(fg2);ficp=get(dyp,''String'');ficp=[ficp ''.eps''];'...
               'orient landscape;lficp=[''print -depsc -noui '' ficp];eval(lficp);']);

fg2ax = axes('Units','pixels',...
   'Parent',fg2,...
   'FontUnits','pixels',...
   'FontSize',txtH,...
   'Position',axPos);

f3tex = uicontrol('Parent',fg2,...
   'Style','text',...
   'Position',[1 axPos(2)-butB-butH butW butH],...
   'FontSize',0.5*txtH,'String','Zoom activated');  

