function sw = surfel_weights(p0,v1,v2,dh,tc)
% Catered to lid driven cavity case.
% returns a 2d cell array, where each row corresponds to a surfel, and 
%   each column corresponds to the pgrams
%   generated by the applicable lattice velocities. Each of these cells
%   contains a variable number of weights, correponding to the lattice 
%   cell touched by the cell's pgram.
% each row entry inside cells are: [i,j, weight, overlap_area, cell_fluid_area]
% As can be inferred, the number of lattice vectors are the same for all
%   segments.

% p0: starting points for every surfel.
% v1: one defining edge of the pgram, common among all pgrams in this case.
% v2: other defining edges of the pgrams corresponding to lattice vectors.

nsurfels = size(p0,1);
nvectors = size(v2,1);

sw = cell(nsurfels,nvectors);
for r = 1:nsurfels
    % for every surfel
    for c = 1:nvectors
        % for every lattice direction
        pgram_area = norm(cross([v1,0],[v2(c,:),0]),2);
        pw = pgram_weights(p0(r,:),v1,v2(c,:),dh);
        pw(1,5) = 0;
        sw{r,c} = pw;
        sw{r,c}(:,4) = sw{r,c}(:,3);
        sw{r,c}(:,3) = sw{r,c}(:,3) / pgram_area;
        for k = 1:size(pw,1)
            cell_fluid_area = tc(tc(:,1) == pw(k,1),:);
            cell_fluid_area = cell_fluid_area(cell_fluid_area(:,2) == pw(k,2),3);
            if isempty(cell_fluid_area)
                cell_fluid_area = dh^2;
            end
            sw{r,c}(k,5) = cell_fluid_area;
        end
        if size(cell_fluid_area) < 1
            disp('Error!!! cell area not found!');
        end
    end
end
    
    
    
    