// Magic Software, Inc.
// http://www.magic-software.com
// http://www.wild-magic.com
// Copyright (c) 2003.  All Rights Reserved
//
// The Wild Magic Library (WML) source code is supplied under the terms of
// the license agreement http://www.magic-software.com/License/WildMagic.pdf
// and may not be copied or disclosed except in accordance with the terms of
// that agreement.

#ifndef WMLGRAPHICS_H
#define WMLGRAPHICS_H

#include "WmlAlphaState.h"
#include "WmlAmbientLight.h"
#include "WmlBezierCylinder.h"
#include "WmlBezierCylinder2.h"
#include "WmlBezierCylinder3.h"
#include "WmlBezierMesh.h"
#include "WmlBezierPatch.h"
#include "WmlBezierRectangle.h"
#include "WmlBezierRectangle2.h"
#include "WmlBezierRectangle3.h"
#include "WmlBezierTriangle.h"
#include "WmlBezierTriangle2.h"
#include "WmlBezierTriangle3.h"
#include "WmlBillboardNode.h"
#include "WmlBound.h"
#include "WmlBoundingVolume.h"
#include "WmlBoundingVolumeTree.h"
#include "WmlBoxBV.h"
#include "WmlBspNode.h"
#include "WmlBspTree.h"
#include "WmlBumpMap.h"
#include "WmlCamera.h"
#include "WmlCameraNode.h"
#include "WmlCapsuleBV.h"
#include "WmlClodMesh.h"
#include "WmlCollapseRecord.h"
#include "WmlCollisionGroup.h"
#include "WmlCollisionRecord.h"
#include "WmlColorRGB.h"
#include "WmlController.h"
#include "WmlConvexRegion.h"
#include "WmlConvexRegionManager.h"
#include "WmlCreateClodMesh.h"
#include "WmlCullState.h"
#include "WmlDirectionalLight.h"
#include "WmlDitherState.h"
#include "WmlDlodNode.h"
#include "WmlFogState.h"
#include "WmlGeometry.h"
#include "WmlGlossMap.h"
#include "WmlIKController.h"
#include "WmlIKGoal.h"
#include "WmlIKJoint.h"
#include "WmlImage.h"
#include "WmlKeyframeController.h"
#include "WmlLight.h"
#include "WmlLightNode.h"
#include "WmlLightState.h"
#include "WmlLozengeBV.h"
#include "WmlMaterialState.h"
#include "WmlMorphController.h"
#include "WmlNode.h"
#include "WmlObject.h"
#include "WmlParticleController.h"
#include "WmlParticles.h"
#include "WmlPixelShader.h"
#include "WmlPlanarReflection.h"
#include "WmlPlanarShadow.h"
#include "WmlPointController.h"
#include "WmlPointLight.h"
#include "WmlPolygonOffsetState.h"
#include "WmlPolyline.h"
#include "WmlPolypoint.h"
#include "WmlPortal.h"
#include "WmlProjectedTexture.h"
#include "WmlRenderer.h"
#include "WmlRendererFont.h"
#include "WmlRenderState.h"
#include "WmlRTTI.h"
#include "WmlScreenPolygon.h"
#include "WmlShader.h"
#include "WmlShaderConst.h"
#include "WmlShaderConstants.h"
#include "WmlShadeState.h"
#include "WmlSkinController.h"
#include "WmlSmallSet.h"
#include "WmlSmartPointer.h"
#include "WmlSpatial.h"
#include "WmlSphereBV.h"
#include "WmlSpotLight.h"
#include "WmlStandardMesh.h"
#include "WmlStateConstant.h"
#include "WmlStream.h"
#include "WmlStringTree.h"
#include "WmlSwitchNode.h"
#include "WmlTerrainBlock.h"
#include "WmlTerrainPage.h"
#include "WmlTerrainVertex.h"
#include "WmlTexture.h"
#include "WmlTextureState.h"
#include "WmlTriMesh.h"
#include "WmlVersion.h"
#include "WmlVertexColorState.h"
#include "WmlVertexShader.h"
#include "WmlWireframeState.h"
#include "WmlZBufferState.h"

#endif
