function results = BVPRect8Results(coord, dn)
% results = BVPRect8Results(coord, dn)
% 8 node rectangular element for 2d BVP
% Computes element solution
% coord = nodal coordinates
% dn = nodal solution
% Output variables are u and its x and y derivatives at element center
x1=coord(1,1); y1=coord(1,2);
x3=coord(3,1); y7=coord(7,2);
a = abs(x3 - x1)/2; b = abs(y7 - y1)/2;
s = 0; t = 0;
u = [-(((a - s)*(b - t)*(b*s + a*(b + t)))/(4*a^2*b^2)),...
        ((a^2 - s^2)*(b - t))/(2*a^2*b),...
        -(((a + s)*(b - t)*(a*(b + t) - b*s))/(4*a^2*b^2)),...
        ((a + s)*(b^2 - t^2))/(2*a*b^2),...
        -(((a + s)*(a*(b - t) - b*s)*(b + t))/(4*a^2*b^2)),...
        ((a^2 - s^2)*(b + t))/(2*a^2*b),...
        -(((a - s)*(b*s + a*(b - t))*(b + t))/(4*a^2*b^2)),...
        ((a - s)*(b^2 - t^2))/(2*a*b^2)]*dn;
dudx= [((b - t)*(2*b*s + a*t))/(4*a^2*b^2), ...
        (s*(t - b))/(a^2*b), -(((b - t)*(a*t - 2*b*s))/(4*a^2*b^2)),...
        (b^2 - t^2)/(2*a*b^2),... 
        ((b + t)*(2*b*s + a*t))/(4*a^2*b^2), ...
        -((s*(b + t))/(a^2*b)), ...
        -(((b + t)*(a*t - 2*b*s))/(4*a^2*b^2)), ...
        (t^2 - b^2)/(2*a*b^2)]*dn;
dudy = [((a - s)*(b*s + 2*a*t))/(4*a^2*b^2),...
        (s^2 - a^2)/(2*a^2*b),...
        ((a + s)*(2*a*t - b*s))/(4*a^2*b^2),...
        -(((a + s)*t)/(a*b^2)),...
        ((a + s)*(b*s + 2*a*t))/(4*a^2*b^2),... 
        (a^2 - s^2)/(2*a^2*b), ...
        ((a - s)*(2*a*t - b*s))/(4*a^2*b^2),...
        ((s - a)*t)/(a*b^2)]*dn;
results=[u, dudx, dudy];