python nmt.py \
    --src=en --tgt=tr \
    --vocab_prefix=/home/burak/Downloads/tur-eng/vocab  \
    --train_prefix=/home/burak/Downloads/tur-eng/train \
    --dev_prefix=/home/burak/Downloads/tur-eng/train  \
    --test_prefix=/home/burak/Downloads/tur-eng/train \
    --out_dir=/tmp/nmt_model \
    --num_train_steps=12000 \
    --steps_per_stats=100 \
    --num_layers=2 \
    --num_units=128 \
    --dropout=0.2 \
    --metrics=bleu
