BoxLayout:
    orientation: "vertical"
    BoxLayout:
        Button:
            size_hint_x: 1
        Button:
            size_hint_x: 1
        Button:
            size_hint_x: 1
    BoxLayout:
        Button:
            size_hint_x: 1
        Button:
            size_hint_x: 2
        Button:
            size_hint_x: 3
    BoxLayout:
        Button:
            size_hint_x: 1
        Button:
            size_hint_x: 0.75
        Button:
            size_hint_x: 0.25
