convert  -colorspace gray  images/middlegen.JPG images/middlegen.eps
convert  -colorspace gray images/frame3.gif images/frame3.eps
convert  -colorspace gray images/jmxconsole.png images/jmxconsole.eps
convert  -colorspace gray images/paper_chain.gif images/paper_chain.eps
convert  -colorspace gray images/jmxmonitor_1.jpg images/jmxmonitor_1.eps
convert  -colorspace gray images/jmxmonitor_2.jpg images/jmxmonitor_2.eps
convert  -colorspace gray images/jmxmonitor_3.jpg images/jmxmonitor_3.eps
convert  -colorspace gray images/jmxmonitor_4.jpg images/jmxmonitor_4.eps
convert  -colorspace gray images/jmxmonitor_5.jpg images/jmxmonitor_5.eps
convert  -colorspace gray images/jmxmonitor_6.jpg images/jmxmonitor_6.eps
convert  -colorspace gray images/jmxmonitor_7.jpg images/jmxmonitor_7.eps
convert  -colorspace gray images/jmxmonitor_8.jpg images/jmxmonitor_8.eps
convert  -colorspace gray images/jmeter_1.jpg images/jmeter_1.eps
convert  -colorspace gray images/jmeter_2.jpg images/jmeter_2.eps
convert  -colorspace gray images/jmeter_3.jpg images/jmeter_3.eps
convert  -colorspace gray images/jmeter_4.jpg images/jmeter_4.eps
convert  -colorspace gray images/jmeter_5.jpg images/jmeter_5.eps
convert  -colorspace gray images/jmeter_6.jpg images/jmeter_6.eps
convert  -colorspace gray images/jmeter_addcar_licenseplatecounter.jpg images/jmeter_addcar_licenseplatecounter.eps
convert  -colorspace gray images/jmeter_aggregate.jpg images/jmeter_aggregate.eps
convert  -colorspace gray images/jmeter_counter.jpg images/jmeter_counter.eps
convert  -colorspace gray images/jmeter_counter_detail.jpg images/jmeter_counter_detail.eps
convert  -colorspace gray images/jmeter_dragdrop.jpg images/jmeter_dragdrop.eps
convert  -colorspace gray images/jmeter_httpdefaults.jpg images/jmeter_httpdefaults.eps
convert  -colorspace gray images/jmeter_jdbc_defaults.jpg images/jmeter_jdbc_defaults.eps
convert  -colorspace gray images/jmeter_jdbc_query.jpg images/jmeter_jdbc_query.eps
convert  -colorspace gray images/jmeter_proxy.jpg images/jmeter_proxy.eps
convert  -colorspace gray images/jmeter_proxy_2.jpg images/jmeter_proxy_2.eps
convert  -colorspace gray images/jmeter_proxy_mozilla.jpg images/jmeter_proxy_mozilla.eps
convert  -colorspace gray images/jmeter_randomizer.jpg images/jmeter_randomizer.eps
convert  -colorspace gray images/jmeter_recorded.jpg images/jmeter_recorded.eps
convert  -colorspace gray images/jmeter_threadgroup.jpg images/jmeter_threadgroup.eps
convert  -colorspace gray images/profiler_1.jpg images/profiler_1.eps
convert  -colorspace gray images/profiler_2.jpg images/profiler_2.eps
convert  -colorspace gray images/profiler_3.jpg images/profiler_3.eps
convert  -colorspace gray images/profiler_4.jpg images/profiler_4.eps
convert  -colorspace gray images/jboss_apache_cluster_simplest.eps images/jboss_apache_cluster_simplest_bw.eps
convert  -colorspace gray images/jboss_apache_cluster_ultimate.eps images/jboss_apache_cluster_ultimate_bw.eps
convert  -colorspace gray images/ejb_distributed.jpg images/ejb_distributed.eps
convert  -colorspace gray images/ejb_distributed_local_wrong.jpg images/ejb_distributed_local_wrong.eps
convert  -colorspace gray images/ejb_distributed_wrong.jpg images/ejb_distributed_wrong.eps
convert  -colorspace gray images/ejb_none_distributed_right.jpg images/ejb_none_distributed_right.eps
convert  -colorspace gray images/jmxconsole_mbean.jpg images/jmxconsole_mbean.eps
convert  -colorspace gray images/jmxconsole_mbean_osstatistics.jpg images/jmxconsole_mbean_osstatistics.eps
convert  -colorspace gray images/jconsole.jpg images/jconsole.eps
convert  -colorspace gray images/jmeter_1.jpg images/jmeter_1.eps
convert  -colorspace gray images/jmeter_2.jpg images/jmeter_2.eps
convert  -colorspace gray images/jmeter_3.jpg images/jmeter_3.eps
convert  -colorspace gray images/jmeter_4.jpg images/jmeter_4.eps
convert  -colorspace gray images/jmeter_5.jpg images/jmeter_5.eps
convert  -colorspace gray images/jmeter_6.jpg images/jmeter_6.eps
convert  -colorspace gray images/dvdplayer.jpg images/dvdplayer.eps
convert  -colorspace gray images/oracle_charset_dbca.jpg images/oracle_charset_dbca.eps
convert  -colorspace gray images/dev_env_flow.png images/dev_env_flow.eps
convert  -colorspace gray images/itracker_benimItracker.jpg images/itracker_benimItracker.eps
convert  -colorspace gray images/itracker_benimItrackerVeli.jpg images/itracker_benimItrackerVeli.eps
convert  -colorspace gray images/itracker_ilkKullaniciEkle.jpg images/itracker_ilkKullaniciEkle.eps
convert  -colorspace gray images/itracker_listeniAzalt.jpg images/itracker_listeniAzalt.eps
convert  -colorspace gray images/itracker_projeYaratildi.jpg images/itracker_projeYaratildi.eps
convert  -colorspace gray images/itracker_projeleriListele.jpg images/itracker_projeleriListele.eps
convert  -colorspace gray images/itracker_sistemBakimi.jpg images/itracker_sistemBakimi.eps
convert  -colorspace gray images/itracker_sorunTestEdilsin.jpg images/itracker_sorunTestEdilsin.eps
convert  -colorspace gray images/itracker_yeniProjeYarat.jpg images/itracker_yeniProjeYarat.eps
convert  -colorspace gray images/itracker_yeniSorunEkle.jpg images/itracker_yeniSorunEkle.eps
convert  -colorspace gray images/ant_path.jpg images/ant_path.eps
convert  -colorspace gray images/cygwin.jpg images/cygwin.eps
convert  -colorspace gray images/cygwin_download_packages_after.jpg images/cygwin_download_packages_after.eps
convert  -colorspace gray images/cygwin_download_packages_before.jpg images/cygwin_download_packages_before.eps
convert  -colorspace gray images/cygwin_download_site.jpg images/cygwin_download_site.eps
convert  -colorspace gray images/accept_test_1.jpg images/accept_test_1.eps
convert  -colorspace gray images/accept_test_2.jpg images/accept_test_2.eps
convert  -colorspace gray images/accept_test_3.jpg images/accept_test_3.eps
convert  -colorspace gray images/accept_test_4.jpg images/accept_test_4.eps
convert  -colorspace gray images/accept_test_5.jpg images/accept_test_5.eps
convert  -colorspace gray images/accept_test_6.jpg images/accept_test_6.eps
convert  -colorspace gray images/accept_test_7.jpg images/accept_test_7.eps
convert  -colorspace gray images/accept_test_8.jpg images/accept_test_8.eps
convert  -colorspace gray images/hibernate_dist_cache.jpg images/hibernate_dist_cache.eps
convert  -colorspace gray images/hibernate_dist_cache_bad.jpg images/hibernate_dist_cache_bad.eps
convert  -colorspace gray images/single_jvm_no_cache.jpg images/single_jvm_no_cache.eps
convert  -colorspace gray images/single_jvm_yes_cache.jpg images/single_jvm_yes_cache.eps
convert  -colorspace gray images/car-web.jpg images/car-web.eps
convert  -colorspace gray images/struts_request_response_action.jpg images/struts_request_response_action.eps
