AddLocationForm:

<AddLocationForm@BoxLayout>:
    orientation: "vertical"
    BoxLayout:
        height: "40dp"  # <1>
        size_hint_y: None
        TextInput:
            size_hint_x: 50  # <2>
        Button:
            text: "Search"
            size_hint_x: 25  # <3>
        Button:
            text: "Current Location"
            size_hint_x: 25  # <3>
    ListView:  # <4>
        item_strings: ["Palo Alto, MX", "Palo Alto, US"]